### ISSUE TITLE
Reading from stdin is a normal flow when stdin is not a tty and should not warn

### ISSUE THREAD

**Issue by chris-morgan** [postcss/postcss-cli#100]
It’s perfectly normal to pipe data to postcss-cli (e.g. in a makefile); that it classifies “no files passed, reading from stdin” as a warning and prints same to the terminal is a bug. There’s no way to indicate that this is the correct and intended behaviour at present (some tools accept `-` as meaning stdin or stdout, as appropriate, but this one doesn’t).

If stdin is a tty, I can understand warning about it. But when it’s not, it *really* shouldn’t produce a warning.

**Comment by RyanZim** [comment]
@chris-morgan I understand what you're saying. In a tty context, it makes sense to notify the user; but in a other situations, it's distracting.

Care to submit a PR that adds a `process.stdin.isTTY` conditional around https://github.com/postcss/postcss-cli/blob/develop/index.js#L158?

**Comment by RyanZim** [comment]
Detecting context isn't so easy; I couldn't figure it out.

@michael-ciniawsky Perhaps we should just remove this warning altogether?
