### ISSUE TITLE
Crash using directory wildcards and watch

### ISSUE THREAD

**Issue by ggascoigne** [postcss/postcss-cli#102]
I'm running  into a crash using v3.0.0-beta.  I have a test project with this sort of layout:

```
src
├── demo
│   ├── App.cssnext
│   ├── App.js
│   ├── App.test.js
│   └── logo.svg
├── index.cssnext
├── index.js
└── variables.cssnext
```

My plan is to convert the *.cssnext into *.css files right next to the *.cssnext files - not ideal but it'll get what I want working in a create-react-app environment.

postcss.config.js:

```js
module.exports = {
  plugins: [
    require('postcss-import')({root:'src'}),
    require('postcss-cssnext')()
  ],
}
```

When I run:

```bash
$ ./node_modules/.bin/postcss -c ./postcss.config.js '**/*.cssnext' -r -x .css -w

                                      /|\
                                    //   //
                                  //       //
                                //___*___*___//
                              //--*---------*--//
                            /|| *             * ||/
                          // ||*               *|| //
                        //   || *             * ||   //
                      //_____||___*_________*___||_____//

✔ Finished src/variables.cssnext (374ms)
✔ Finished src/index.cssnext (399ms)
✔ Finished src/demo/App.cssnext (403ms)
{ Error: ENOENT: no such file or directory, open '**/*.cssnext'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '**/*.cssnext' }
```

Note that the error only seems to occur when a change to one of the *.cssnext files gets changed.

I should add that if I don't use the `-w` option then the command completes correctly.

**Comment by RyanZim** [comment]
This is a known bug. It was reported in https://github.com/postcss/postcss-cli/issues/95 and fixed in https://github.com/postcss/postcss-cli/pull/97. However, the fix has not yet been released.

I'm hoping to get v3.0.0 shipped in the next few days, which will include this bugfix. Currently, I'm waiting on @michael-ciniawsky to make one final PR to clean up what needs done for v3.0.0.

**Comment by michael-ciniawsky** [comment]
@RyanZim `v3.0.0-beta.2` ? 🙃 Don't wait for idiots like me,  if there is a known regression and it got fixed beta +1 or patch release asap :D

**Comment by RyanZim** [comment]
I've been considering making that release; what's the status of your PR?

**Comment by michael-ciniawsky** [comment]
1-2 days 😛

**Comment by RyanZim** [comment]
v3.0.0 is shipped! :tada: Sorry so long.
