### ISSUE TITLE
Keep in sync CHANGELOG.md and Release notes

### ISSUE THREAD

**Issue by sylvainpolletvillard** [postcss/postcss-cli#104]
https://github.com/postcss/postcss-cli/blob/develop/CHANGELOG.md is not in sync with https://github.com/postcss/postcss-cli/releases, which confused some people looking for breaking changes in v3

Maybe choose one or the another ?

**Comment by RyanZim** [comment]
@sylvainpolletvillard Good point. I was debating: what's the best way to write the release notes for v3.0.0? List the changes since the latest beta, since 2.x, or both?

**Comment by sylvainpolletvillard** [comment]
Both I guess ?

**Comment by RyanZim** [comment]
@sylvainpolletvillard I was leaning in that direction, but wanted a second opinion. :slightly_smiling_face: 

I'll try to update the CHANGELOG when I get a chance.

**Comment by RyanZim** [comment]
Fixed: c33ae87d506e97484c16505ffabe7f90df55361.

**Comment by RyanZim** [comment]
v3.0.0 is shipped! :tada:
