### ISSUE TITLE
Watch task does not start over if error occurred in v3

### ISSUE THREAD

**Issue by andrejsm** [postcss/postcss-cli#105]
If I have any error during development, process exits and I have to start it over. I expect watch task to start over automatically whenever I change any of files again even if an error occurred before.

**Comment by RyanZim** [comment]
@andrejsm Thanks for reporting; I didn't realize that v2 behaved this way. I will fix this as soon as I can get to it.

**Comment by RyanZim** [comment]
Will be fixed in v3.0.0

**Comment by andrejsm** [comment]
Thank you
