### ISSUE TITLE
Offer a way to output only to STDOUT/STDERR

### ISSUE THREAD

**Issue by Ryuno-Ki** [postcss/postcss-cli#110]
PostCSS could be used for various tasks.

Usually you are interested in STDOUT/output into a file for further processing.
However, if you are writing a linting PostCSS plugin the main interest is STDERR.

In order to write cross-platform code it would be helpful to define a way how to handle those two streams and offer one or the other.

Default behaviour should be to write to both.

Result of #93 and #98

**Comment by RyanZim** [comment]
@michael-ciniawsky @Ryuno-Ki Do you have any thoughts on the optimal API for this?

**Comment by michael-ciniawsky** [comment]
@Ryuno-Ki Simply writing to both `process.stdout/process.stderr` would solve your Issue in addition with a `--silent` flag ?

Please elaborate futher on a particular usecase for this, for e.g a linting plugin could simply use the PostCSS Messages API (PostCSS writes them to STDERR) or use a `console.warn/console.error()` itself

**Comment by michael-ciniawsky** [comment]
Do want to get the warnings/errors as logs just written to the stream (STDERR) for whatever reason ? 😛

**Comment by Ryuno-Ki** [comment]
As I explained in https://github.com/postcss/postcss-cli/issues/93#issuecomment-286428916 I need a way to compute the target in a node module.

From an *NIX point of view, the API would look like
```js
stdout = computeStdOut()
stderr = computeStdErr()

module.exports = {
    // …
    stdout: stdout,
    stderr: stderr
}
```
but that does not read JavaScript-ish.

What about stick to `module.exports.to` for _stdout_ and `module.exports.errorTo` for _stderr_?

**Comment by Ryuno-Ki** [comment]
@michael-ciniawsky Where would you write the results out? Where would I need to put the code in?

**Comment by michael-ciniawsky** [comment]
@Ryuno-Ki Can you link me to actual code for clearification please ? 😛 Maybe it would be better to wrap PostCSS in a Transform Stream yourself and integrate that into your library instead of the whole CLI

```js
const { Transform } = require('stream')
const postcss = require('postcss')

module.exports = function postcssStream (plugins = [], options = {}) {
  const stream = new Transform()

  stream._transform = (chunk, enc, cb) => {
      postcss(plugins)
        .process(chunk.toString(enc), options)
        .then((result) => cb(null, result.css))
    }
  }

  return stream
}
```


```js
process.stdin
   .pipe(postcssStream(plugins, options))
   .pipe(process.stdout)
```


```js
fs.createReadStream('path/to/src/file.css')
   .pipe(postcssStream(plugins, options))
   .pipe(fs.createWriteStream('path/to/dest/file.css'))
```

**Comment by michael-ciniawsky** [comment]
Of course change to logic to you particular needs then :D

**Comment by Ryuno-Ki** [comment]
I'm currently assigned to two projects, one which shall be released soon. For the other I need those postcss functionality. Will come back with my findings this week.

**Comment by RyanZim** [comment]
@Ryuno-Ki Just thought of something: If you're just running a linter that doesn't change the CSS, why don't you just use `--replace`?

**Comment by Ryuno-Ki** [comment]
Haven't found time yet, since priorities were shifted :-/

**Comment by Ryuno-Ki** [comment]
Looking at https://github.com/postcss/postcss-cli/issues/110#issuecomment-287308088 now, I can only see how to deal with STDOUT (`.pipe(process.stdout)`). Is there a way to access errors?

I'm comfortable with grunt, but less with gulp …
However, it looks like [piping is a NodeJS feature](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options).

Is there an `error` event I can listen to? Accordint to [StackOverflow there seem to be one](http://stackoverflow.com/a/22389498) but the NodeJS docs are kind of vague.

**Comment by michael-ciniawsky** [comment]
@Ryuno-Ki Yep the Node has a Unix Stream Implementation on it's own.

In the example above the callback in `then((result) => cb(null, result.css))` is a so called error first with the parameter signature `cb(err, data)`, accepting an Error as first argument.

```js
const { Transform } = require('stream')
const postcss = require('postcss')

module.exports = function postcssStream (plugins = [], options = {}) {
  const stream = new Transform()

  stream._transform = (chunk, enc, cb) => {
      postcss(plugins)
        .process(chunk.toString(enc), options)
        .then((result) => cb(null, result.css))
        .catch((err) => cb(err))
    }
  }

  return stream
}
```

```
process.stdin
   .pipe(postcssStream(plugins, options))
    .on('error', (err) => process.stderr.write(err, 'utf8'))
   .pipe(process.stdout)
```

Other ways are possible,you could even emit your own Error Event when implementing it in your stream implementation :)

**Comment by Ryuno-Ki** [comment]
I'll give it a spin next week. Enjoy your weekend!

**Comment by Ryuno-Ki** [comment]
I did some homework!

Okay, so our PostCSS plugin look similar to [this one](https://github.com/hail2u/node-css-mqpacker/blob/ef253da7d968abb27a04f389246e01b6f12e833e/lib/css-mqpacker.js#L146). Imagine it had a `css.warn` inside of `css.eachAtRule`, like [documented in PostCSS documentation](http://api.postcss.org/postcss.html#.plugin). Our plugin uses [walkRules](http://api.postcss.org/Rule.html#walkRules).

So I created a npm script like the following:
```js
'use strict'
const fs = require('fs')
const cssPlugin = require('path/to/postcss/plugin.js')
var options = {'foo': 'bar'}

process.stdin
   .pipe(cssPlugin(options))
   .on('error', (err) => process.stderr.write(err, 'utf8'))
   .pipe(process.stdout)

fs.createReadStream('path/to/css/*.css')
   .pipe(cssPlugin(options))
   .pipe(fs.createWriteStream('tmp.css'))  // Will be discarded
```

When I execute it through node I get
```sh
$ node postcssProcessing.js
_stream_readable.js:501
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:501:8)
    at Object.<anonymous> (/path/to/postcssProcessing.js:ROW:COLUMN)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
```

That's surprising, since [ReadableStreams ought to have an `on` handler](https://nodejs.org/docs/latest-v4.x/api/stream.html#stream_class_stream_readable).

**Comment by RyanZim** [comment]
@Ryuno-Ki Why don't you just use postcss-cli with the `--replace` flag?

**Comment by michael-ciniawsky** [comment]
@Ryuno-Ki Readable Stream? You need a Transfrom Stream and add your plugin to `_transform` 😛

**Comment by Ryuno-Ki** [comment]
I'm currently assigned to another team and won't be able to investigate further before June 2017.

**Comment by RyanZim** [comment]
@Ryuno-Ki ping?

**Comment by Ryuno-Ki** [comment]
­*on what project I worked back then …

However, I am not assigned to it any longer. I am closing this issue as Won't Fix.
