### ISSUE TITLE
Ability to use several configs in same project

### ISSUE THREAD

**Issue by tegner** [postcss/postcss-cli#112]
In v2.6.0 it was possible to have disting config files for separate destinations, I can't seem to find a way to do this in v3 with postcss-load-config.

Is there any way to achieve this?

**Comment by RyanZim** [comment]
@tegner There are several ways to do this.

- If you just want a slightly different config for production and development, you can use `context.env` in your config file, along with the `--env` flag. https://github.com/postcss/postcss-cli#context
- If you want a different config for css sources in different folders, you can use multiple config files out of the box. For example, if you have two folders containing your source CSS, if you put a config file in each folder, files in the one folder will be processed using the config file in that folder; the files in the other folder will use the other config file.
- If you want to have your config files in a different folder, you can use the `--config` option. (By default, config file lookup starts at the source CSS file.) This option could also be used to specify the config to use, though the configs would have to be in different folders. A bit hacky, but it works.

If I were you, I would try to use `context` if possible.

Hope this clears things up for you. Let me know how it goes.

**Comment by tegner** [comment]
@RyanZim Thank you for your quick reply, it looks like the context solution solved it for me. Thank you.

**Comment by piotr-cz** [comment]
Can I have somehow multiple configs in one folder or the file name `postcss.config.js` is harcoded?

for example
```
/config/postcss.library.config.js
/config/postcss.bookmarlet.config.js
```

**Comment by RyanZim** [comment]
@piotr-cz It's hardcoded.

**Comment by piotr-cz** [comment]
That's quite uncommon; actually I see something liket that for the first time
