### ISSUE TITLE
browsers entry in package.json isn't respected

### ISSUE THREAD

**Issue by sarukuku** [postcss/postcss-cli#114]
Please see https://github.com/postcss/autoprefixer/issues/786. It appears to be an issue with the `postcss-cli` version `3.0.0`.

Andrey Sitnik thinks it might be an issue related to `postcss-cli` not sending the current file path to plugins.

**Comment by RyanZim** [comment]
@sarukuku Are you positive you're using postcss-cli v3.0.0 and not v3.0.0-beta? (run `npm update` to be sure). There was a bug in v3.0.0-beta that could cause behavior like this.

**Comment by RyanZim** [comment]
Issue here might be due to use passing a relative path for `from`.

**Comment by sarukuku** [comment]
> Are you positive you're using postcss-cli v3.0.0 and not v3.0.0-beta?

I'm fairly sure. I don't have the CLI installed globally and in the folder I rand the command I installed always an exact version of the CLI.

**Comment by RyanZim** [comment]
Try the latest `master`:
```
npm uninstall postcss-cli
npm install postcss/postcss-cli
```
See if that fixes your issue.

**Comment by sarukuku** [comment]
With a quick test in the project I found this issue in I'd say that doesn't help. I think I need to do a minimal test repo so that we can all test it. Will link it here soon.

**Comment by sarukuku** [comment]
Ok, [here's](https://github.com/sarukuku/postcss-cli-test) the repo. Now the setup should be minimal enough to reason about the root cause of this.

What I can tell now based on this is that when I pipe css in to postcss it doesn't work. If I don't pipe it in but let postcss read the file on its own it works. In the example it might a look a bit weird that I do `cat css/test.css` and then pipe it. It's there just to play the role of a "preprocessor". In my full setup I use `node-sass` to preprocess my scss file and then pipe the result from it to autoprefixer.

Instructions on how to use the repo and the two tests can be found from the readme.

**Comment by michael-ciniawsky** [comment]
@sarukuku I this case it isn't possible to solve your isssue on the CLI level, PostCSS can only reason about the file location (path), when passed via options (metadata) explicilty. Since the CLI has no way to provide this information when recieving the CSS as `{String}` via STDIN (`process.stdin`), this needs to be solved in autoprefixer or to be more precise in [browserslist](https://github.com/ai/browserslist) [here](https://github.com/ai/browserslist/blob/master/index.js#L333)



### #1 Hotfix

**browserlist/index.js**
```js
...
browserslist.findConfig = function (from) {
   if (!from) from = process.cwd() // <=

   return eachParent(from, function (dir) {
   ...
```

### #2 Refactor

[cosmiconfig](https://github.com/davidtheclark/cosmiconfig)

**browserlist/index.js**
```js
...
browserslist.findConfig = function (from) {
   if (!from) from = process.cwd() // <=

   return cosmiconfig('browserslist', {..options})
           .load(from)
           .then((pkg) => parsePackage(pkg))
           .then((config) => browserslist.readConfig(config))
...
```

@sarukuku Send PR 😛 

 cc @ai

**Comment by ai** [comment]
Maybe we should pass `from = process.cwd() + '/stdin.css'` in case of `stdin` input in `postcss-cli`?

Having `from = process.cwd()` in Browserslist could not be clear for user and will increase bad Browserslist usage when developers forget to pass `from`.

**Comment by michael-ciniawsky** [comment]
@ai `~.process(css, { from: file })` accepts a directory or must the path contain a base?

**Comment by ai** [comment]
@michael-ciniawsky It should be a file (I think directory will work too, but it could falls in some edge cases)

**Comment by RyanZim** [comment]
@ai Won't passing `from = process.cwd() + '/stdin.css'` mess up source maps?

**Comment by ai** [comment]
@RyanZim interesting question. Right now we have `<CSS input 1>` and it is not really better than fake path `process.cwd() + '/stdin.css'`. Anyway we don’t have correct path in source map (`<CSS input 1>` is not really correct value for source maps, only path are accepted). So `process.cwd() + '/stdin.css'` will be still fine for source maps in my opinion.

**Comment by RyanZim** [comment]
OK, PR welcome. If this causes problems, I'll revert this change though.

**Comment by sarukuku** [comment]
One thing I don't understand though it that why this works with the `postcss-cli` version `2.6.0`? If in the example repo I provided I downgrade `postcss-cli` from version `3.0.0` to version `2.6.0` both of the npm scripts (`works` / `doesntwork`) produce correct results. With version `3.0.0` only the `doesntwork` script produces wrong results.

**Comment by RyanZim** [comment]
Hard telling; v3.0.0 was a total rewrite.

**Comment by michael-ciniawsky** [comment]
@sarukuku Did you set `from` in the old config format ?

**Comment by sarukuku** [comment]
@michael-ciniawsky nope, in my last test the only thing I changed in the example repo was the version of `postcss-cli`. So to me it looks piping worked in version `2.6.0` but doesn't work anymore in `3.0.0`.
