### ISSUE TITLE
lib folder is missing in npm package

### ISSUE THREAD

**Issue by benurb** [postcss/postcss-cli#117]
Hello,

thanks for your really handy tool. Unfortunately it seems to be broken in version 3.1.0 on npm. The npm package is missing the entire lib folder, which obviously leads to a `Error: Cannot find module './lib/depGraph'`.

Test: `curl https://registry.npmjs.org/postcss-cli/-/postcss-cli-3.1.0.tgz | tar -x`. In the `package` folder there is no subfolder `lib`.

Best regards,
Ben

**Comment by RyanZim** [comment]
Oops, I forgot we had a `files` property in the package.json. https://github.com/postcss/postcss-cli/blob/master/package.json#L41

Will fix that and publish v3.1.1 ASAP.

**Comment by RyanZim** [comment]
Done https://github.com/postcss/postcss-cli/releases/tag/v3.1.1
