### ISSUE TITLE
-c/--config does respect targeted config file

### ISSUE THREAD

**Issue by jonsuh** [postcss/postcss-cli#118]
I’d like to be able to selectively choose the correct config file; however, passing the `--config` flag does not seem to respect the targeted file.

I have two files:
```
config.postcss.json
config.postcss.dist.json
```

Running the following:
```
postcss --config config.postcss.json --dir assets/css assets/css/*.css
postcss --config config.postcss.dist.json --no-map --dir dist/assets/css assets/css/*.css
```

`config.postcss.json` looks like the following:
```
{
  "parser": "",
  "plugins": {
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    }
  }
}
```

While `config.postcss.dist.json` looks like the following:
```
{
  "parser": "",
  "plugins": {
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    },
    "cssnano": {
      "safe": true
    }
  }
}
```

I’d consider using `context.env` based on your suggestion in https://github.com/postcss/postcss-cli/issues/112 but I’m creating a build tool for developers and would like the ease of customization to have a low entry barrier; therefore I find having 2 separate config files easier to manage for novices.

**Comment by jonsuh** [comment]
As a follow-up, I have also tried the config files as JS files and the `--config/-c` flag still fails to respect the targeted config files.

```
postcss --config config.postcss.dev.js --dir assets/css assets/css/*.css
postcss --config config.postcss.dist.js --no-map --dir dist/assets/css assets/css/*.css
```

```
// config.postcss.dev.js
module.exports = {
  parser: "",
  plugins: {
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    }
  }
}
```

```
// config.postcss.dist.js
module.exports = {
  parser: "",
  plugins: {
    "autoprefixer": {
      "browsers": ["last 2 versions"]
    },
    "cssnano": {}
  }
}
```

**Comment by jonsuh** [comment]
So followed the conversation in https://github.com/postcss/postcss-cli/issues/55, I concluded that the only way to pass in a custom config is to have `postcss.config.js` in a separate directory and pass the directory name via `--config`
```
config-directory/
- postcss.config.js
```
```
postcss --config ./config-directory --dir assets/css assets/css/*.css
```

Is there a particular reason you can’t target a specific file and one is only required to use the `postcss.config.js` filename?

**Comment by RyanZim** [comment]
> Is there a particular reason you can’t target a specific file and one is required to use the postcss.config.js filename?

Simply put, we use https://github.com/davidtheclark/cosmiconfig, which is set up to hard-code the filename.

**Comment by jonsuh** [comment]
@ryanzim Ah, understood. Could an argument be made to allow some level of control over the filename? e.g. Two config files in a directory.

For standardization I understand some level of filename requirements (e.g. `.config.js`, `.rc`) but also allowing some slight variations to the filename From user input.

Looks like it’s `postcss-load-config` that hard sets the config filename https://github.com/michael-ciniawsky/postcss-load-config/blob/master/index.js#L48 

Terrible idea to allow the user to override of the value of the first argument `postcss`? So instead of assuming the filename is `postcss.config.js` it could be `custom.config.js` or `.customrc` and would allow for multiple config files in the same directory.

Would require @michael-ciniawsky’s input to have `postcss-load-config` to allow this.

**Comment by michael-ciniawsky** [comment]
@jonsuh As @RyanZim stated out, the hardcoded name is set by cosmiconfig, but since `postcss.config.js` should function as a 'common' config with the goal to work across all builds tools (webpack, Gulp, Grunt, CLI), this behaviour is even benefical to that. Allowing to override the config name will cause confusion and bugs imho. What you what to achieve is taking care of by `context` already, where `ctx.env` distinguishes between `development/production` dynamically. The only 'downside' is you need to use `config.js`, returning a function for this. The `.json, .(yml|yaml), package.json` configs are more for making your own plugin packages and require that in your projects `postcss.config.js` afterwards (Grouping). If you need completely different configs in different folders, use the **Config Cascade**

**`NODE_ENV = 'development'` (default)**
```
postcss ... # === postcss.config.js
```
**`NODE_ENV = 'production'`**
```
NODE_ENV='production' postcss ... # === postcss.dist.config.js
```
**postcss.config.js**
```js
module.exports = ({ file, options, env }) => ({ // { file, options, env } = context
  parser: file.extname === '.sss' ? 'sugarss' : false 
  plugins: {
    'postcss-import': { root: file.dirname }
    'cssnano': env === 'production' ? { safe: true } : false // env === process.env.NODE_ENV
  }
})
```

**Comment by jonsuh** [comment]
Understood. Thanks for the explanation and examples. I’ll either choose to do the `context` route or find an alternate solution. Thank you.
