### ISSUE TITLE
Have an error "Input Error: Did not receive any STDIN" when using code a-la "cat input.css | postcss [OPTIONS] > output.css"

### ISSUE THREAD

**Issue by discodanser** [postcss/postcss-cli#119]
In simple example it work as sample from readme 
`"cat style.css | postcss -u cssnano > output.css"`
and also as
`"cat style.css | postcss -u cssnano -o output.css`

With more complex string 
`"postcss -u autoprefixer < style.css | postcss -u cssnano > style.css"`
catch error "Input Error: Did not receive any STDIN".

But `"postcss -u autoprefixer < style.css | postcss -u cssnano -o style.css"` still working.

Features:
 - STDOUT working (`"postcss -u autoprefixer < style.css"` show printout);
 - switch places for autoprefixer and cssnano does not matter;
 - windows or ubuntu does not matter.

**Comment by michael-ciniawsky** [comment]
```diff
- "postcss -u autoprefixer < style.css | postcss -u cssnano > style.css"
+ "postcss -u autoprefixer | postcss -u cssnano -o style.css"
```

Why not `postcss -u autprefixer -u cssnano -o style.css` ? 😛 

You are not writing to STOUT and pipe the result from the first run to the next

**Comment by RyanZim** [comment]
@michael-ciniawsky Even shorter:

    cat style.css | postcss -u autoprefixer cssnano -o style.css

**Comment by RyanZim** [comment]
@discodanser If you're trying to edit your file in place, just use the `--replace` (`-r`) option:

    postcss style.css -u autoprefixer cssnano -r

**Comment by discodanser** [comment]
**michael-ciniawsky**, **RyanZim**

Thnx, that is much better. :)
Before that I used separately
```
postcss style.css -u autoprefixer -r
postcss style.css -u cssnano -r
```
But it was not cool of course.

Question appeared when I found [answer from SO](http://stackoverflow.com/questions/35197836/npm-with-node-sass-and-autoprefixer). And wonder why it does not work for me.

**Comment by RyanZim** [comment]
@discodanser That SO thread was written before postcss-cli v3 was released.

Going to close this out since it seems this is a usage issue.
