### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#123]
```
  1 test failed [21:00:18]



  error › invalid --config
  /home/ryan/postcss-cli/test/error.js:44

   43:   .then(({ err, code }) => {                         
   44:     t.is(code, 1, 'expected non-zero error code')    
   45:     t.regex(err, /ENOENT: no such file or directory/)

  Actual:

    0

  Expected:

    1

  expected non-zero error code
```

Attn: @michael-ciniawsky 

I suspect this has something to do with the latest patch version of cosmiconfig, will investigate later if no one else beats me to it.

**Comment by michael-ciniawsky** [comment]
This error  `/ENOENT: no such file or directory/` was removed with the latest cosmiconfig update 

https://github.com/davidtheclark/cosmiconfig/issues/63
https://github.com/davidtheclark/cosmiconfig/pull/64

**Comment by RyanZim** [comment]
OK, thanks for doing the lookup!

It seems that we should still error out somehow if the config fails to load.

**Comment by michael-ciniawsky** [comment]
Yep, but I don't now how yet tbh 😛 Now they shifted the responsibility for all their crap on us again, suckers.... 😛 I also need to add something like [`resolve-from`](https://www.npmjs.com/package/resolve-from) to `postcss-load-config`, because currently, if the CLI is installed globally it fails atm, (it doesn't `require()` the plugins from `process.cwd()`) I fix it soon when time :)

**Comment by RyanZim** [comment]
> I also need to add something like resolve-from to postcss-load-config, because currently, if the CLI is installed globally it fails atm, (it doesn't require() the plugins from process.cwd()) I fix it soon when time :)

Ugh; that's why it's good to use devDependencies + npm scripts

**Comment by michael-ciniawsky** [comment]
Yep I also prefer it that way, but the fix is easy and it's nothing urgent 😛

**Comment by RyanZim** [comment]
@michael-ciniawsky Is this worth fixing, or do we just remove that test and leave things as they are?
