### ISSUE TITLE
Cannot get cssnano to work with .postcssrc.js or postcss.config.js

### ISSUE THREAD

**Issue by nwmcsween** [postcss/postcss-cli#124]
Below is my .postcssrc.js, specifically it seems the test(ctx.file.basename) isn't working for some reason?

````
module.exports = (ctx) => ({
  'no-map': true,
  plugins: {
    'postcss-easy-import': {},
    'stylelint': {},
    'postcss-cssnext': {
      browsers: ['> 5%', 'not IE < 11'],
      autoprefixer: {
        cascade: false,
        flexbox: "no-2009",
        grid: false
      }
    },
    'css-mqpacker': {},
    'cssnano': /.+\.min\.css$/.test(ctx.file.basename) ? {} : false,
    'postcss-reporter': {}
  }
})
````

**Comment by RyanZim** [comment]
`.postcssrc` only works with json or yaml; rename your file to `postcss.config.js` and it should work fine.

**Comment by nwmcsween** [comment]
It still seems to not work when renaming postcssrc.js to postcss.config.js

**Comment by RyanZim** [comment]
@nwmcsween Please make a reduced test case repo, push it to GitHub, and post the link here. Thanks!

**Comment by michael-ciniawsky** [comment]
@nwmcsween Coud you try without 'no-map: true' && `'cssnano': /.+\.min\.css$/.test(ctx.file.basename) ? {} : false,` for initial debugging please, for the latter I recommend to use `ctx.env` instead => `ctx.env === 'production' ? { safe: true } : false` :stuck_out_tongue:

**Comment by nwmcsween** [comment]
I figured out what the issue was, I assumed ctx.file.* was the output file (as it makes sense since the operations are on the resulting file) and did `postcss somefile.css -o somefile.min.css` in a makefile and thus postcss-cli didn't apply cssnano.

**Comment by michael-ciniawsky** [comment]
> Maybe ctx could include an output file as well?

What would be the usecase for this ? 😛 The config is applied **per file** _before_ it gets processed by postcss

**Comment by nwmcsween** [comment]
Very simple, the old cli way of using -u plugin --plugin options (and better imo) allows applying rules to uncreated files e.g. with Make `MERGED_MIN := $(MERGED:=.css=.min.css)` at which point you could apply cssnano to the $(MERGED_MIN) as a target.

**Comment by RyanZim** [comment]
Closing this old discussion thread
