### ISSUE TITLE
Combine --watch and --replace for same file causes infinite loop in console

### ISSUE THREAD

**Issue by vlatkodrljin** [postcss/postcss-cli#126]
Following CLI command causes infinite loop:

`postcss public/css/styles.css -u autoprefixer -r -w --poll`

When I change styles.css the watch starts command again and again in console.
Without --watch option everything is working as expected.

**Comment by RyanZim** [comment]
@vlatkodrljin Using `-w` and `-r` together isn't possible, since postcss-cli will pick up replacements as a file change, triggering an infinite loop.

This is an edge-case I never thought of; we should fix this to make it error out instead of getting stuck in the infinite loop.

**Comment by vlatkodrljin** [comment]
I have infinite loop only when my postcss parsing is longer than 100ms.

Chokidar which this CLI uses has default pool interval of 100ms, and reason for my infinite loop is because my parsing interval is out of that 100ms.

We can add option for setting polling interval in this particular case, this would be the best solution if you ask me.

**Comment by RyanZim** [comment]
@vlatkodrljin That's a hacky way around the real issue. Most users aren't using `--poll`.

**Comment by santanajames** [comment]
@RyanZim I agree that @vlatkodrljin method is a hack around the real issue. However, generally, if ---poll is an option then --interval is also an option - same as Chokidar which is used in this case. It is beneficial to have control over the polling interval if you are one of those users who uses it. 

I have made a pull request with this addition.

**Comment by weaintplastic** [comment]
I'm running into the same issue. Would be great to have a solution for it.
