### ISSUE TITLE
watch mode shouldn't terminate when a plugin errors

### ISSUE THREAD

**Issue by cmnstmntmn** [postcss/postcss-cli#127]
**app.css**

```css
@import 'other.css'
```

**postcss.config.js**
```js
module.exports = ctx => ({
  map: ctx.options.map,
  plugins: [
      require("postcss-import")
  ]
});
```

**run**
`postcss app.css -o output.css -w`

**return**

```console
Error: Failed to find 'other.css'
    in [ 
        /Users/....
    ]
    at /Users/.../node_modules/postcss-import/lib/resolve-id.js:48:11

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 start: `postcss app.css -o output.css -w`
npm ERR! Exit status 1
```

**Comment by RyanZim** [comment]
@cmnstmntmn This is the way postcss-import works; postcss-import throws an error when a file isn't found. This behavior has received some controversy, but we've never decided if it should be changed or not.

Anyhow, closing since this is due to postcss-import, not postcss-cli.

**Comment by RyanZim** [comment]
Hey there, just noticed your comment in gitter; I didn't realize you were talking about watch mode, sorry.

Yes, this is something we should look into.

**Comment by arxpoetica** [comment]
Agreed, this shouldn't error. It's really messing with my mojo. 😬 😜  For real though, I have a BUNCH of watching cli scripts for different tasks (rollup, pug/jade, sass), and this is the one that kills my main watching process (for multiple scripts) everytime it errors.

Watch should _convey_ the error, but keep on a watching.

**Comment by RyanZim** [comment]
PR welcome, I just haven't gotten a chance to fix this yet.

**Comment by arxpoetica** [comment]
Word.
