### ISSUE TITLE
autoprefixer does not work or deletes majority of .css file half the time (using postcss-cli)

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [postcss/postcss-cli#130]
apologies for posting this issue on 2 different forums, i am not sure of the etiquette or protocol in github, as i am very new to it!

this is my problem:

https://github.com/postcss/autoprefixer/issues/844

does this look like an autoprefixer issue or a postcss-cli issue?

THANKS.

**Comment by RyanZim** [comment]
@Learn-Digital-Audio You can't use `watch` and `replace` at the same time, see https://github.com/postcss/postcss-cli/issues/126.

**Comment by Learn-Digital-Audio** [comment]
Thanks!
