### ISSUE TITLE
CLI watch mode not watching @imports in Node.js 8.x.x

### ISSUE THREAD

**Issue by swashcap** [postcss/postcss-cli#136]
#### Problem

The `--watch` flag doesn’t watch CSS `@import` dependencies for changes and re-process after a dependency CSS file is changed. (`@import` dependencies are regular CSS files, inlined using [postcss-import](https://github.com/postcss/postcss-import).)

#### Expected

The `--watch` flag should watch CSS `@import` files for changes, re-process on change, and output a new file. This works in Node.js 7.10.0.

#### Example

Reproduce with this setup:

1. Install Node.js 8+
2. Install _postcss-cli_ and _postcss-import_:

    ```shell
    $ npm install postcss-cli postcss-import
    ```

3. Add these files:

    ```css
    /* main.css */
    @import 'alert.css';
    ```

    ```css
    /* alert.css */
    .alert {
      background: hotpink;
      color: white;
      padding: 1rem;
    }
    ```

    ```js
    // postcss.config.js
    const atImport = require('postcss-import')

    module.exports = {
      plugins: [
        atImport()
      ]
    }
    ```
4. Run in a shell:

    ```shell
    $ node_modules/.bin/postcss main.css --watch -o main-processed.css
    ```
5. Edit a property in _alert.css_. Observe no re-processing occurs.

#### Environment

* **OS:** OS X 10.12.5
* **Node:** 8.0.0
* **npm:** 5.0.1
* **postcss-cli:** 4.0.0

**Comment by swashcap** [comment]
Important discovery: this problem _only occurs when using vim to edit files_.

![watput](https://cloud.githubusercontent.com/assets/1858316/26667306/51bfabf6-4659-11e7-9cef-f3b116581602.gif)

_postcss-cli_ seems to see a swap file (created at _app/css/._alert.css.swp_) when vim opens the file. None of vim's writes appear to be observed.

Works totally fine in VS Code!

**Comment by swashcap** [comment]
Here’s the same setup, in Node.js 7.10.0:

![in-node-7](https://cloud.githubusercontent.com/assets/1858316/26667451/28b1a2e0-465a-11e7-8799-6d96c48e88c4.gif)

_Confounding._

**Comment by swashcap** [comment]
Looks like _[chokidar](https://github.com/paulmillr/chokidar)_, which _postcss-cli_ uses to watch files, has some failing tests on Node.js 8: paulmillr/chokidar#607

**Comment by RyanZim** [comment]
@swashcap Thanks for reporting, yep, this is probably related to chokidar.

**Comment by RyanZim** [comment]
Closing as I haven't heard further reports of this.

**Comment by BalaWxd** [comment]
For those may have similar issue using VIM can take a look of this link https://github.com/webpack/docs/wiki/troubleshooting#file-saves-in-webstorm-dont-trigger-the-watcher.
