### ISSUE TITLE
When installed locally, postcss doesn't write to a file

### ISSUE THREAD

**Issue by hamlim** [postcss/postcss-cli#137]
Tested a simple case where I installed `postcss-cli` locally inside a project, and then installed it globally:

Locally installed and run via yarn:
```
yarn postcss src/**/*.css --dir dist/public
```
provided the compiled output straight to the console but didn't write to a file

Globally installed (`yarn global add postcss-cli`):
```
postcss src/**/*.css --dir dist/public
```
compiled the src file and wrote the file correctly to the output directory.

I am just getting started using postcss but I would expect the local version to work the same exact way that the globally installed version worked.

**Comment by RyanZim** [comment]
@hamlim That's strange, I'm using the a local installation with zero issues. Perhaps you can create a reduced test case?

**Comment by hamlim** [comment]
Made a testing repo here: https://github.com/hamlim/postcss-failing-local-compile with steps to reproduce.

**Comment by RyanZim** [comment]
@hamlim You're using the local installation incorrectly. Uninstall postcss-cli globally, then run the passing script. postcss-cli works as intended. Your problem is that your failing script unnecessarily prefixes `yarn` to the script.

**Comment by hamlim** [comment]
That test case might not actually be accurate then because I still run into the issue, when installing postcss-cli locally via yarn the only way to run it is via `yarn postcss`.
