### ISSUE TITLE
postcss-cli ignoring config

### ISSUE THREAD

**Issue by mfolkeseth** [postcss/postcss-cli#143]
I can't get postcss-cli to read the config either by default (current directory) or by using the `-c`flag. Using Node v 8.0.0 and npm v 5.0.4. Have tried to downgrade Node all the way down to 6.1.0.

However, the `-u`-flag works fine. here is my `postcss.config.js`

```
const autoprefixer = require('autoprefixer');
const customProperties = require('postcss-custom-properties');
const cssnano = require('cssnano');

module.exports = {
  parser: 'postcss',
  plugins: [
    autoprefixer,
    customProperties,
    cssnano
  ]
};
```
Using postcss v 6.0.3 and postcss-cli v 6.0.1. Am I missing something?

**Comment by RyanZim** [comment]
Try:

```js
module.exports = {
  parser: 'postcss',
  plugins: [
    autoprefixer(),
    customProperties(),
    cssnano()
  ]
};
```
If that doesn't fix this, please make a reproducible test case repo and post the link here. Thanks!

**Comment by michael-ciniawsky** [comment]
`parser: 'postcss' `? 🙃

**Comment by RyanZim** [comment]
@michael-ciniawsky Yeah; good catch. @mfolkeseth You can drop that line from your config.

**Comment by mfolkeseth** [comment]
https://gist.github.com/mfolkeseth/5a012c17686d6fdf6c1b827327e434ab

@RyanZim Is this sufficient?

**Comment by RyanZim** [comment]
@mfolkeseth Would have been better to include a package.json as I suspect this is a specific version issue. I added my own; here's a working example: https://gist.github.com/RyanZim/21e062284783c975c4a8a7de9ce45bc7

Run `npm test` to test this; it works fine for me. Note that I removed the `-c` option from your command; it's not needed.

**Comment by RyanZim** [comment]
Assuming this is fixed.
