### ISSUE TITLE
Passing options to plugins on the command line

### ISSUE THREAD

**Issue by ao2** [postcss/postcss-cli#144]
Hi,

IMHO it is not very clear how to pass options to plugins enabled with the `--use` option.

I experienced this with autoprefixer: at the beginning I was having a hard time figuring out how to pass the "browsers" option to it.

Another `postcss-cli` implementation (https://github.com/pirxpilot/postcss-cli) uses the syntax `--${plugin}.option value` which in my case would be something like `--autoprefixer.browsers "> 1%"`, but that didn't work with the "official" `postcss-cli`.

I later figured out a way to solve my particular problem using environment variables:

```
BROWSERSLIST="invalid" \
./bin/postcss --no-map --use autoprefixer < ../../css/style.css
```

However it would be handy if the other mechanism was supported too, which could even be applied to other plugins.

As an example, the following command line currently has the same effect as not passing any `browsers` option at all:

```
./bin/postcss --no-map --use autoprefixer --autoprefixer.browsers "invalid" < ../../css/style.css
```

A patch like the following improves the situation:

```diff
--- index.js.orig	2017-07-04 17:09:22.328881652 +0200
+++ index.js	2017-07-04 17:22:13.402544610 +0200
@@ -153,7 +153,7 @@ let config = {
   plugins: argv.use
     ? argv.use.map((plugin) => {
       try {
-        return require(plugin)()
+        return require(plugin)(argv[plugin])
       } catch (e) {
         error(`Plugin Error: Cannot find module '${plugin}'`)
       }
```

After that the option is passed along: to verify this the extreme case of an invalid query is reported to the user:

```
⠋ Processing stdinYour current PostCSS version is 6.0.5, but autoprefixer uses 5.2.17. Perhaps this is the source of the error below.
✖ Processing stdin
{ [BrowserslistError: Unknown browser query `invalid`]
  name: 'BrowserslistError',
  message: 'Unknown browser query `invalid`',
  browserslist: true }
```

I am not a Javascript developer, so I don't know if the patch above is the best solution.

Thanks,
   Antonio

**Comment by ao2** [comment]
The ambiguity in my case came also from the fact that https://github.com/ai/autoprefixer-cli suggests https://github.com/pirxpilot/postcss-cli but when doing `yarn add postcss-cli` https://github.com/postcss/postcss-cli gets installed instead, and a newbie like me could end up following the documentation from the former while actually executing the latter.

**Comment by RyanZim** [comment]
From the docs: 

> _If you need to pass options to your plugins_, or have a long plugin chain, you'll want to use a configuration file.

https://github.com/postcss/postcss-cli#config

This is where you need a config file. Passing complex options to your plugins in the command is a bad practice IMO. Also, you should probably simply be using a browsers config in your package.json.

The note at `autoprefixer-cli` should probably be changed; ping @ai.

**Comment by remorse** [comment]
I realize this is not going to change, but it's *really* inconvenient to have to create a separate config file. It would be much handier to be able to include options in a command line, because then you don't have to copy files around in addition to the script you're using.

**Comment by remorse** [comment]
Also, how are you supposed to pass options when you aren't working on a project, but just a snippet of text that may never be saved to the file system?

**Comment by RyanZim** [comment]
postcss-cli (and postcss itself to a degree) is built with projects in mind, it's inherently a lot of config for just snippets.
