### ISSUE TITLE
Plugins search tool

### ISSUE THREAD

**Issue by hzlmn** [postcss/postcss-cli#145]
Hello guys, 

I am planning to write module for searching plugins in `cli` (kind like `postcss-parts` for `cli`) and wondering do you want to make this as a part of `postcss-cli` or it's out the project's scope and should be separate package?

> Just for now it will use same data. In future i plan to add smarter data aggregation across different sources.

cc @ai

**Comment by RyanZim** [comment]
@hzlmn That's a great idea! Out of scope IMO, but I might consider linking to your project from the readme here. Let me know when it's done!

**Comment by hzlmn** [comment]
Sure. Thank you @RyanZim
