### ISSUE TITLE
-m option doesn't work on 4.1.0

### ISSUE THREAD

**Issue by WataruTamanaha** [postcss/postcss-cli#147]
-m option doesn't work after updated to 4.1.0.
It will have inline sourcemap if I set "map: true" in postcss.cpnfig.js.

**Comment by RyanZim** [comment]
In v4.0.0 and later, inline source-maps are default. Passing the `-m` option will create external sourcemaps instead. Passing `--no-map` turns off sourcemaps altogether. Isn't it working this way for you?

**Comment by WataruTamanaha** [comment]
Sorry for the delay.

Yes I understand -m option.
I wrote the task below:

```
"scripts": {
    "watch:css": "postcss src/css/main.pcss -o public/dist/css/main.css -w"
},
```

No inline sourcemap appears in main.css.
Also -m option doesn't create external sourcemap.
v2.6.0 does work.

**Comment by WataruTamanaha** [comment]
If I set `map: true `in postcss.cpnfig.js, inline sourcemap will be inserted through having `--no-map`.
I want to have sourcemap only in watch mode. So I thought of having two config files, one is for watch task and other one for build task specifing with `--config` option.

But it doesn't look smart way..

**Comment by michael-ciniawsky** [comment]
Please setup a test repo for debugging or provide more info about your setup (configs, `tree $PROJECT` etc...)

**Comment by WataruTamanaha** [comment]
Hi, this is the repository
https://github.com/cdgrph/npm-scripts-sample

Thank you for your assist!

**Comment by michael-ciniawsky** [comment]
> ⚠️  If you want to set options via CLI, it's mandatory to reference `ctx.options` in `postcss.config.js`

```bash
postcss input.pcss -o output.css -m
```

**postcss.config.js `{Function}`**
```diff
+ module.exports = (ctx) => ({
+ map: ctx.options.map, // <= this line
  plugins: {
    'postcss-import': { root: ctx.file.dirname },
    'postcss-cssnext': {},
    'cssnano': ctx.env === 'production' ? {} : false
  }
})
```

This was a necessary evil to keep CLI and Config usage consistent 😛 , you need to reference `options` CLI flags in the config via `ctx`

**Comment by WataruTamanaha** [comment]
@michael-ciniawsky 

Excuse me that I didn't read through the reference.
Thank you for helping me out!
