### ISSUE TITLE
"Plugin error: Cannot find module". Can't get CLI options to work for me.

### ISSUE THREAD

**Issue by nlazzari** [postcss/postcss-cli#149]
I've gone through many different combinations of config and terminal commands and I'm not able to get PostCSS CLI to work. I've tried these commands:

`postcss -c config/postcss.config.js -u postcss-cssnext --dir dist/css src/client/css/*.css`
`postcss -u postcss-cssnext --dir dist/css src/client/css/*.css`

My package.json:

```
 "devDependencies": {
           . . .
    "postcss": "^6.0.8",
    "postcss-cli": "^4.1.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-scss": "^1.0.2",
           . . .
  }
```

Finally, postcss.config.js:

```
module.exports = {
	plugins: [
		require('precss')({}),
		require('postcss-cssnext')({}),
		require('postcss-scss')({})
	]
}
```

Any ideas ? I'm a bit frustrated - between PostCSS, PostCSS-CLI, and other plugin pages they each suggest different config and methods, none of which have worked for me.

**Comment by michael-ciniawsky** [comment]
```
postcss -c config/postcss.config.js -u postcss-cssnext --dir dist/css src/client/css/*.css
```

Either use `postcss.config.js` or `-u` both together doesn't/shouldn't work :)

**postcss.config.js**
```diff
module.exports = {
+     syntax: 'postcss-scss', // I'm not sure you will actually need it
	plugins: [
		require('precss')(),
		require('postcss-cssnext')(),
-		require('postcss-scss')({})
	]
}
```

```
Plugin Error: Cannot find module (?)
```

Which module isn't found, this normally indicates a dependency (e.g plugin) is missing 😛

**Comment by nlazzari** [comment]
Thanks for the info!

OK, I tried the `-c` and `-u` options each separately, and still get errors.

When I run `postcss -c postcss.config.js`, I get the error:
`✖ Input Error: Did not receive any STDIN`

When I run `postcss -u postcss-postcssnext`, I get the error:
`✖ Plugin Error: Cannot find module 'postcss-postcssnext'`

Since `postcss-postcssnext` is in my `package.json.devDependencies`, I'm not sure how else to register the plugin with PostCSS ?

**Comment by michael-ciniawsky** [comment]
> ✖ Input Error: Did not receive any STDIN

File I/O needs to be **exclusively** provided via CLI only, (**not** in `postcss.config.js`)

```bash
postcss path/to/input --dir|--output path/to/output [--config path/to/config*]
```
* ⚠️ 
```
postcss -c postcss.config.js
```

You only need `-c|--config` if you store the config in a 'nested' folder e.g `.config` [or have multiple ones]

```
|– .config
| |– [postcss.config.js] (manually [--c|config])
|-src
| |– [postcss.config.js] (automatically [2])
| |– css  
| | |– index.css
| | |– [postcss.config.js] (automatically [1])
|-dist
|
|– postcss.config.js (automatically [3])
|- package.json
```

`postcss.config.js` lookup always starts from `dirname(file)` and uses the first config found, stops at `os.homedir()` (Config Cascade). It's recommended to simply place the config in './' and forget about it :)  

> ✖ Plugin Error: Cannot find module 'postcss-postcssnext'

'postcss-postcssnext'  should be 'postcss-cssnext'?  Could you with another plugin e.g `postcss-nested` if this is a bug ?

**Comment by nlazzari** [comment]
Thanks very much for your detailed response! I was able to get it working because of your guide :).

I used this command
`postcss src/client/css/*.css --dir dist/css --config config/postcss.config.js`

with this config
```
module.exports = {
	plugins: [
		require('postcss-import'),
		require('postcss-cssnext')({
			browsers: 'last 2 versions',
			verbose:  true
		}),
		require('cssnano')({
			preset: 'default',
		})
	]
}
```

However I do get a warning about autoprefixer duplicates? I didn't think any of the above plugins also included `autoprefixer`:
```Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.```

Very happy this is working now :). One last question, when is it necessary to apply the `--use` flag? From my reading I saw that some plugins (like `cssnext`) just run automatically in order, and others need to be invoked with a `--use` flag. Is this correct, if not how is this applied ?

Thanks!

**Comment by RyanZim** [comment]
Both `postcss-cssnext` and `cssnano` include autoprefixer under the hood. You want to turn off autoprefixer in `cssnano`; I forget how to do it.

The `--use` flag is for when you aren't using a config file (i.e. when you don't need to pass options to plugins).
