### ISSUE TITLE
Error out when using -w when writing to stdout

### ISSUE THREAD

**Issue by gaoxiaosong1113** [postcss/postcss-cli#156]
I used File Watchers in webstorm to add autoprefixer to suggest an error
![image](https://user-images.githubusercontent.com/16183057/29904392-3288755e-8e3b-11e7-8ff6-23f60ee28565.png)

postcss-cli、autoprefixer version
![image](https://user-images.githubusercontent.com/16183057/29904466-83890aa4-8e3b-11e7-984f-0c509eb6ce61.png)

What is the reason for that?

**Comment by michael-ciniawsky** [comment]
```diff
- ...-o -w
+ -o path/to/dist -w  
```

From the screenshot it's seems to be a command line args mismatch and the result is logged to `STDOUT` atm, because no path is given to `-o|output`

```bash
postcss $INPUT -u $PLUGINS -o $OUTPUT -w
```

**Comment by RyanZim** [comment]
We should modify our logic here to error out with a friendly error message.

**Comment by gaoxiaosong1113** [comment]
@michael-ciniawsky  
Thanks for your prompt, my network storm editor has been successfully configured.
But the editor set file watchers configuration less add autoprefixer, my mac becomes very cardton, I also need to find other ways to optimize, or replace the editor.

**Comment by RyanZim** [comment]
Reopening to remind me to add an error message.
