### ISSUE TITLE
4.1.1 not published

### ISSUE THREAD

**Issue by billyjanitsch** [postcss/postcss-cli#157]
Hi @RyanZim, I noticed that version 4.1.1 was released on Github, but hasn't been published to npm. You can verify by running `npm info postcss-cli versions`.

**Comment by RyanZim** [comment]
Good catch!

**Comment by RyanZim** [comment]
Fixed, sorry for the wait.

**Comment by billyjanitsch** [comment]
No worries, thanks so much for your work on this project!
