### ISSUE TITLE
Using postcss-cli and .css file syntax error unknown word !important

### ISSUE THREAD

**Issue by ms-clovis** [postcss/postcss-cli#158]
When I was testing postcss from the command line on a Windows 7 64bit machine the following appears:
```
x Processing css_other\main.css


x Syntax Error: css_other\main.css

 [438:28] Unknown word

  436 |     margin: 18px 0 50px 0;
  437 |     width: inherit;
> 438 |     display: inline-block; !important;
      |                            ^
  439 | }
  440 |
```

Note the red arrow points to the exclamation point before important

**Comment by RyanZim** [comment]
You have a syntax error in your CSS. `display: inline-block; !important;` is not valid. `display: inline-block !important;` is the correct format.
