### ISSUE TITLE
--config discussion

### ISSUE THREAD

**Issue by vphantom** [postcss/postcss-cli#165]
Hello,

This is possibly related to #143: postcss-cli ignores `-c` and `--config` entirely.  I can specify a non-existent file, a valid file, it doesn't matter.  The only work-around I found short of downgrading was to temporarily copy my configuration file to `postcss.config.js` in the current directory in order to run postcss.

This is using postcss-cli 4.1.1 on Node 6.11.4.  This regression seems to have been brought on by the new argument parsing in [v4.1.0...v4.1.1](https://github.com/postcss/postcss-cli/compare/v4.1.0...v4.1.1) but I can't quite put my finger on it.

**Comment by vphantom** [comment]
With v4.1.0 however, specifying a file did work. However of course I now see that `--help` does mention that it is now a path instead.

May I ask why the change, though?  Since the configuration fits in a single file, why not specify it directly?  That would allow a use case like ours, where the file is neatly stashed away as a dot-file.

**Comment by RyanZim** [comment]
It was supposed to be a directory since v3; however, specifying a file also worked (thought we weren't aware of that).

Given the amount of confusion I've seen around this option, I'm strongly leaning towards changing the behavior to point to a file in the next major release.

**Comment by michael-ciniawsky** [comment]
I'm still not getting what doesn't work anymore 🙃  ? `postcss --config path/to/.config/postcss.config.js` vs. `postcss --config path/to/.config` ? 

@vphantom Can you `tree $PROJECT` and post it. In most cases the `--config` shouldn't be necessary

**Comment by vphantom** [comment]
I'm not sure what you mean by `tree $PROJECT` but we're simply storing our configuration in `.postcss.config.js` to keep it as a dot-file (like many others such as: `.eslintrc.json`, `.gitignore`, etc.) neatly away from our main files.

Therefore, we used to use `postcss --config .postcss.config.js` and as of v4.1.1, we now have to first `cp .postcss.config.js postcss.config.js` temporarily, then run `postcss`, then `rm postcss.config.js` to clean up.

**Comment by michael-ciniawsky** [comment]
`.postcssrc.js` should work for `.dotfiles`

`tree` is UNIX Command Line Tool to visualize a file tree/directory structure

**Comment by RyanZim** [comment]
> I'm still not getting what doesn't work anymore :upside_down_face: ? postcss --config path/to/.config/postcss.config.js vs. postcss --config path/to/.config ?

@michael-ciniawsky `postcss --config path/to/.config/postcss.config.js` used to work; now you have to do `postcss --config path/to/.config`.

**Comment by vphantom** [comment]
@michael-ciniawsky You're right, `.postcssrc.js` works without specifying `--config` at all. :smile:

**Comment by michael-ciniawsky** [comment]
> @michael-ciniawsky postcss --config path/to/.config/postcss.config.js used to work; now you have to do postcss --config path/to/.config

`postcss --config path/to/` is the correct way since `postcss-load-config` like ESLInt and all other tools using cosmiconfig under the hood look for base names based on the following filename conventions

`pgk.postcss {Object}` (`package.json`)
`.postcssrc.js {Function}`
`.postcssrc.json {Object}`
`.postcssrc.{yml,yaml} {Object}`
`postcss.config.js {Function}`

Specifying the filename/a custom filename === `{Error}` 😛
