### ISSUE TITLE
Shouldn't be able to use --dir and -o together

### ISSUE THREAD

**Issue by TheSuperFly** [postcss/postcss-cli#166]
Hello, 

I'm experiencing some issues by executing this command:
```
postcss components/**/*.css --dir 'wouldBeIgnoredAnyway' -o 'styles/app.css'
```

It compiles every source files well but output only contains the last compiled file. 

I've checked the source code, that's because `css()` does `fs.outputFile()` which overwrite content every time one input get proceed.

Yet, I did a little fix on a fork available here : https://github.com/TheSuperFly/postcss-cli/tree/fix/overwritting. I'll create a pull request when a maintainer confirms that's a real issue and not a bad usage.

**Comment by michael-ciniawsky** [comment]
This is bad usage as implicit concatenation should be avoided, please use `postcss-import` instead with the `--dir dest/` flag in case you have multiple dest CSS files (`complete1.css, complete2.css, ...` etc).

**Comment by RyanZim** [comment]
That's poor usage; `--dir` and `-o` are supposed to be mutually exclusive. It is a bug that postcss-cli doesn't throw an error when you use them together.

**Comment by TheSuperFly** [comment]
Ok, I see. So if you don't want this issue to be filled again, either we should trigger an error to avoid this behavior of overwritting or handle it nicely by handling multiple inputs when one output is expected, like `sass`'s cli does transparently.

AHMA, option two is the way to go since I've been using postcss in a react (next.js) context where stylesheet belongs to components and should not require to edit global reference for being used, added or removed.

In my fork, I did a `fs.append()` on each compilation which could make a live reload system go crazy. But as an improvement, I can hold an certain amount of compiled sources in memory then commit then if we're about to meet a memory leak.

Now you choose! 😄

**Comment by RyanZim** [comment]
Yeah, going to trigger an error here. Implicit concatenation isn't something I want, since I can't guarantee the order the files are appended to the output will always be consistent.

**Comment by TheSuperFly** [comment]
Alright!

**Comment by michael-ciniawsky** [comment]
Yep, should throw. `next.js` (`webpack`) file structure is out-of-scope
