### ISSUE TITLE
4.1.1 claims to be slower than 4.1.0 but is not

### ISSUE THREAD

**Issue by vphantom** [postcss/postcss-cli#167]
(This is not a bug, merely an observation which you may find interesting.)

I was shocked to see postcss-cli's reported time become slower by an order of magnitude after the update to v4.1.1 so I investigated.  First I ruled out plugins by disabling all of them entirely, then I timed the command itself with the UNIX `time` program:

Version | Plugins | User CPU | PostCSS claims
--------|---------|----------|---------------
4.1.0 | none | 1.6 s | 170 ms
4.1.1 | none | 1.6 s | 1.20 s
4.1.0 | yes | 2.7 s | 200 ms
4.1.1 | yes | 2.9 s | 2.35 s

Considering that you have always been using `process.hrtime(time)` I guess this comes from dropping `Math.round()` in favor of `prettyHrtime()`, although the resulting difference is surprising.

**Comment by RyanZim** [comment]
The old logic only used `process.hrtime(time)[1]`, which completely screws time logic if it took more than 1s. I discovered this was buggy, so I switched to `prettyHrtime`. The new time figures are correct; the old ones were terribly screwed.
