### ISSUE TITLE
Allow external sourcemaps when writing to STDOUT

### ISSUE THREAD

**Issue by whaaaley** [postcss/postcss-cli#169]
Is there any reason this is currently impossible? I get an error:

`✖ Output Error: Cannot output external sourcemaps when writing to STDOUT`

My use case is the following:

`postcss dist/app.css -u autoprefixer -m | cleancss -o dist/app.css`

I'm using external source maps with STDOUT with rollup, babel, uglifyjs, node-sass and cleancss. This is the only place where I get hung up. Any explanation at all would be helpful. Thanks.

**Comment by RyanZim** [comment]
@whaaaley I'm not sure what you mean by "external sourcemaps"; If you're piping to STDOUT, why would you want to write sourcemaps to an external file? Inline sourcemaps are generated by default.

**Comment by whaaaley** [comment]
By external source maps I mean map files and not inline with the source. I want to write to an external source map because the package I'm piping to accepts an external source map without any config. I use external source maps for everything, they seem to perform better when passing them in and out of multiple projects.

**Comment by RyanZim** [comment]
You could pipe through https://github.com/thlorenz/exorcist to write to the external sourcemap. This is and edge-case usage IMO.

**Comment by whaaaley** [comment]
I disagree that this is an edge case. Not supporting external source maps just because inline source maps work seems like the wrong approach. Regardless, edge case or not, this is how all of the projects I listed work as well. They all support external source maps with STDOUT.

**Comment by michael-ciniawsky** [comment]
@whaaaley Which package supports that, so we can take a look at how this package enables this ? I'm pretty sure you either need a marker to the intermediate source map `/*# sourceMappingURL='path/to/file.ext.map' */`or inlined it as `base64` encoded BLOB `/*# sourceMappingURL=data:application/json;base64, ... */` into the file itself.

**Comment by whaaaley** [comment]
@michael-ciniawsky Yeah, it could be via marker. That actually makes more sense. I had just assumed it was based on input file name. I'd imagine `babel-cli` or `rollup` might be the best projects to reference for this. I'm using both of those projects right now in my scripts, but I'm only using STDOUT with babel-cli.

Here's an example of passing babel output into uglify with STDOUT.

First I bundle my JS and make an external source map with the `-m` flag, with the `sourceMappingURL` comment.
```
rollup src/app.js -o dist/app.js -f iife -m inline -c
```

When building for prod, I also run this command. I give Babel an input and it also modifies the external source map file, then it's again modified by uglify, although sadly with some extra config on uglify's part.
```
babel dist/app.js | uglifyjs -o dist/app.js -c -m --source-map "url='app.js.map',content='dist/app.js.map'" &
```

**Comment by michael-ciniawsky** [comment]
> I give Babel an input and it also modifies the external source map file

Does it also work if you pipe to `babel` directly `rollup | babel | uglifyjs` ? Sure picking up previous source maps should already be possible (not 💯  if `postcss` picks up `/*# sourceMappingURL=data:application/json;base64, ... */ comments but I think so), e.g

**postcss.config.js**
```js
const { readFileSync } = require('fs')

modules.exports = ({ file, options, env }) => ({
   map: { prev: JSON.parse(readFileSync(`${file}.map`), 'utf8')) },
   plugins: { ...plugins }
})
```

> Although sadly with some extra config on uglify's part, but at least it works.

That's because it isn't sufficiently possible to `tee` (`split`) the stream, the next program needs to parse the marker in the stream (e.g via `RegExp`) when being piped to. Reading external maps via it's own logic (e.g `fs`) is `!==` supporting external maps via `STDOUT`. The de facto 'standard' here is `RegExp` parsing.

> `rollup-plugin-babel` && rollup-plugin-uglify` would do you a great service 😛 

**rollup.config.js**
```js
import babel from 'rollup-plugin-babel'

// for `uglify-es` support (ES2015+)
import { minify } from 'uglify-es'
import uglify from 'rollup-plugin-uglify'

// or process.env.NODE_ENV ('development/production')
const env = !process.env.ROLLUP_WATCH

export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    sourcemap: true
  },
  plugins: [
    babel()
    env && uglify({}, minify)
  ]
}
```

Anyways, you need to **exactly** describe your use case and what other CSS workflow related CLI programs you intend to use. Otherwise it is simply difficult to triage eventual missing funtionality

**Comment by whaaaley** [comment]
> Does it also work if you pipe to babel directly rollup | babel | uglifyjs ?
Can't say for sure. I don't have a use for that. I can test later if it makes a difference?

> rollup-plugin-babel && rollup-plugin-uglify would do you a great service 😛
Thanks but no thanks. I'm aware this is an option and I used rollup's config files for years but it requires too much work to separate your production and development processes.

> Anyways, you need to exactly describe your use case and what other CSS workflow related CLI programs you intend to use. Otherwise it is simply difficult to triage eventual missing funtionality
My use case is in my original post.

Perhaps the `--source-map` flag could optionally take a value of the location of the input file so source map knows where to output.

**Comment by michael-ciniawsky** [comment]
> Can't say for sure. I don't have a use for that. I can test later if it makes a difference?

Don't bother, it is likely `babel` parses the comments and if it is a URL is loads the map from disk. 

> Thanks but no thanks. I'm aware this is an option and I've used rollup's config files for years but it requires too much work/config to separate your production and development processes. CLI workflows solve that.

It's out-of-scope for this issue and use what you like the most, but `ENV` (`process.env`) variables may help you in the future.

```
"scripts": {
  "dev": "NODE_ENV=development rollup -c -w", 
  "prod": "NODE_ENV=production rollup -c"
}
```

> My use case is in my original post.

Which needs more info about the setup you intend to use? What other CLI programs are involved (e.g  `sassc`,  `lessc`, `clean-css`, `none`) ? Do they support parsing `/* sourceMappingURL= .. */` ? etc etc... Is all you need a `file.css.map` written to disk when piping to `STDOUT` ?

**Comment by whaaaley** [comment]
> It's out-of-scope for this issue and use what you like the most, but ENV (process.env) variables may help you in the future.

Thanks, but I'm already aware of env vars as well. This is part of the config insanity I was referring to. I'd prefer working with CLIs only at this point.

> Which needs more info about the setup you intend to use? What other CLI programs are involved (e.g sassc, lessc, clean-css, none) ?

I use node sass in another task before passing it to my production task with postcss and cleancss, but not with STDIO.

> Do they support parsing /* sourceMappingURL= .. */ ?

`clean-css` does not, but you can pass it a source map like this, however it only seems to work with STDIN. If this project is ever updated to output external source maps with STDOUT I'll be sure to post an issue there too 👍 .

`cat dist/app.css | cleancss -o dist/app.css --source-map dist/app.css`

> Is all you need a file.css.map written to disk when piping to STDOUT ?

Yup.

**Comment by RyanZim** [comment]
I'm still not clear on why this is needed; closing this old thread, can revisit if needed.

**Comment by whaaaley** [comment]
_sourcemap support_

Don't worry about it. I suppose I'll figure it out myself.
