### ISSUE TITLE
Sources Content

### ISSUE THREAD

**Issue by whaaaley** [postcss/postcss-cli#182]
There's no way to enable sources content. This is a problem for me as I don't serve my source with my bundle.

**Comment by RyanZim** [comment]
I'm not sure I understand?

**Comment by whaaaley** [comment]
Sourcemaps have a feature called `sourcesContent` see the follow:
https://sourcemaps.info/spec.html#h.mofvlxcwqzej

This is so you can have sourcemaps without actually serving the original source in the same directory.

**Comment by RyanZim** [comment]
@whaaaley Not sure if this can be set in the config file or not; see http://api.postcss.org/global.html#processOptions If not, you'll have to use the API directly; the CLI is just for the 80% use-case.

**Comment by whaaaley** [comment]
This is a simple feature and it's something that's supported by literally every other CLI I use in my project.

**Comment by whaaaley** [comment]
For anyone seeing this in the future...

Turns out you can circumvent this lack of functionality by passing in a source map that already contains a `sourcesContent` prop. Postcss core will see that and "bootstrap" it for you. At least postcss core knows how to treat a source maps properly...
