### ISSUE TITLE
postcss-cli --base option does not work

### ISSUE THREAD

**Issue by DongShelton** [postcss/postcss-cli#190]
postcss version: 6.0.8
postcss-cli version: 4.1.1

I am using postcss-cli and I have a folder structure like this  
```
src
|
|---components
|    |   
|___ |---index.css
```
I am running:
```shell
postcss src/**/*.css --dir lib/ --base
```
And it is excepted like this
```
lib
|
|---components
|    |   
|___ |---index.css
```
But I got this:
```
lib
|---index.css
```
It doesn't keeping the directory structure. Did I made something wrong?

**Comment by RyanZim** [comment]
postcss src/**/*.css --dir lib/ --base src/

should work.

**Comment by DongShelton** [comment]
I used the command you gave me, but why I got this: 
```
lib
|---User
|---|---<myname>
|---|---|---Document
|---|---|---|---project
|---|---|---|---|---lib
|---|---|---|---|---|---components
|---|---|---|---|---|---|---index.css
```

**Comment by RyanZim** [comment]
My tree:
```
.
├── lib
└── src
    └── components
        └── index.css
```

    postcss src/**/*.css --dir lib --base src/

results in:
```
.
├── lib
│   └── components
│       └── index.css
└── src
    └── components
        └── index.css
```
on Linux. What's your OS?

**Comment by DongShelton** [comment]
The problem has been solved.
When I use this on OS X
```shell
postcss src/**/*.css --dir lib/ --base /src
```
it would result in above.
But this two command work correctly:
```shell
postcss src/**/*.css --dir lib/ --base src
postcss src/**/*.css --dir lib/ --base src/
```
The key is whether there is "/" and where that be place

**Comment by WhynoChinese** [comment]
I use your command is worked,but I used npm script to compile only one ！
![image](https://user-images.githubusercontent.com/11802308/35390022-ef3e2b92-0214-11e8-8b9a-e80b00c8a7b5.png)

this is the result:
![image](https://user-images.githubusercontent.com/11802308/35390048-0c8786da-0215-11e8-80af-e7fab89dbe67.png)

But it is good to execute it on the command line
![image](https://user-images.githubusercontent.com/11802308/35390149-59614b9e-0215-11e8-9cbd-cbc990856d7e.png)
