### ISSUE TITLE
Make output optional

### ISSUE THREAD

**Issue by vincentorback** [postcss/postcss-cli#2]
Adding `false` as an optional value to the output option: `-o false` would be great if you just want to parse CSS. The main reason for this is linting for me but I assume there might be other use cases where you use postcss for parsing.

**Comment by corysimmons** [comment]
We're discussing API in https://github.com/postcss/postcss-cli/issues/1

Care to migrate your issue there and close this one?

**Comment by vincentorback** [comment]
Ah of course!
