### ISSUE TITLE
Watch triggering only once

### ISSUE THREAD

**Issue by WishCow** [postcss/postcss-cli#20]
I'm probably missing something trivial, but I can't get watch to work. I'm using:

```
./node_modules/.bin/postcss -u precss -w -o static/out.css css/base.css
```

If I make a change to base.css, it is reflected in out.css, but after that, no other changes will trigger the rebuild. If I ctrl-c the postcss process, and start again, it works again for 1 modification. No output from the postcss process.

```
    "postcss": "^5.0.19",
    "postcss-cli": "^2.5.1",
    "precss": "^1.4.0"

npm version 3.8.6
node version 5.10.1
distro is arch linux
```

**Comment by RyanZim** [comment]
@WishCow I am unable to reproduce with:
```
"postcss-cli": "^2.5.2",
"precss": "^1.4.0"
$ node -v
v6.2.2
$ npm -v
3.9.5
distro is Lubuntu
```
Is this still an issue for you?

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by DavidOliver** [comment]
I also have this issue in postcss-cli 4.1.1 in both Node 8 and 9, in Linux. (KDE Neon, which is Ubuntu 16.04 LTS + the KDE desktop environment.)

However, adding the `--poll` option to the command allows for watching to work for more than one source file update:

    ./node_modules/.bin/postcss source/styles/test.css -o public/test.css -w --poll

Let me know if there's any further information I should provide. Thanks!

**Comment by RyanZim** [comment]
@DavidOliver Not sure what the cause of this is, but `--poll` is there to allow you to handle cases where watching doesn't work correctly. For now, just use `--poll`, unless you figure out what the root cause is.

**Comment by mkoelll** [comment]
I just had the same issue, you just need to [increase the amount of inotify watchers](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers). 

Probably also related to #44.
