### ISSUE TITLE
How to reference postcss.config.js from CLI?

### ISSUE THREAD

**Issue by alucardu** [postcss/postcss-cli#203]
I've created a `postcss.config.js` in the root folder of my project:

    module.exports = {
        plugins: [
          require('autoprefixer')({grid: true})
        ]
    }

How do I reference postcss to use that config file? I run this command from my /src/css folder: `postcss -w default.css -w default.css --use autoprefixer --output build/default.css`  but there's no reference/link to my `postcss.config.js` file.

**Comment by RyanZim** [comment]
You don't need to explicitly reference the config file; just run `postcss <input_file> -o <output_file> -w` and it should read your config.
