### ISSUE TITLE
Run postcss-cli globally?

### ISSUE THREAD

**Issue by alucardu** [postcss/postcss-cli#204]
When I install `npm install postcss-cli -g` and then run `postcss default.css -o build/default.css -w` it doesn't use my `postcss.config.js` file: 

        module.exports = {
            plugins: [
            require('autoprefixer')({grid: true})
            ]
        }

When I install it in the project I postcss-cli does use my `postcss.config.js` file. Is it possible to use postcss-cli as standalone so I don't have to integrate it into the project.

**Comment by RyanZim** [comment]
@alucardu Global usage should work fine. I just tried it and it works. Is the `postcss.config.js` file in the same directory as where you're running the command?

**Comment by RyanZim** [comment]
Yep.

**Comment by zor-el** [comment]
I do have the same issue as @alucardu (global postcss-cli ignores `postcss.config.js`.  It it's unclear how this is resolved. @RyanZip, could you perhaps share _how_ you made this work for you from a global install?

**Comment by RyanZim** [comment]
Now, with postcss v8; postcss and postcss-cli must be installed separately. I would strongly advise against trying to run postcss-cli globally. Install as a devDependency, and use npm scripts.

**Comment by zor-el** [comment]
> I would strongly advise against trying to run postcss-cli globally.

But why is that? It works fine apart from config thing.

**Comment by RyanZim** [comment]
Because postcss v8 relies on `peerDependencies`; which are a pain to troubleshoot with global installs.
