### ISSUE TITLE
Autoprefixer not working with CLI

### ISSUE THREAD

**Issue by RichardFelix** [postcss/postcss-cli#209]
I am running postcss-cli and trying to use autoprefixer on my css file. When I run the command on my css file it gets processed and finishes with no autoprefixing on output.css.  Please help, thank you in advance.
  
cat dist/public/css/style.css | postcss -u autoprefixer > dist/public/css/output.css --no-map 

"devDependencies": {
    "autoprefixer": "^8.3.0",    
    "postcss-cli": "^5.0.0"
}

**Comment by RyanZim** [comment]
Command should be

    cat dist/public/css/style.css | postcss -u autoprefixer --no-map > dist/public/css/output.css

What's your input CSS? Are you sure it needs prefixes? Do you have a `browserslist` config in your package.json?

**Comment by RichardFelix** [comment]
Tried that command and still have the same issue.  I have added my input css file below.  Yes, it does need prefixes.  No, I do not have a browerslist config in my package.json.

This is my input CSS file, something simple for testing purposes.
/* input css file */
body {
  background-color: #000;
  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 1fr 1fr;
  grid-template-areas: "sidebar sidebar";
 }

.sidebar {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  grid-area: sidebar; 
}
  .sidebar .box {
    background-color: #000; 
}

**Comment by RyanZim** [comment]
You're running this command in an npm script?

**Comment by RichardFelix** [comment]
Yes, I am running this command in a npm script.  I have also tried it in the command line manually.  Both have the same issue.  I have tried this on both windows 10 and ubuntu 16.04 LTS.

**Comment by RyanZim** [comment]
Confirmed issue. This is super weird, because other plugins work just fine, but autoprefixer doesn't. @ai any ideas?

**Comment by RichardFelix** [comment]
Thanks, I got it to work setting the postcss.config.js file to grid: true.  I thought grid was on by default like it was when I used gulp for autoprefixing. This is the postcss.config.js and script I used to get it to work.

// postcss.config.js
module.exports = {
    plugins: [
      require('autoprefixer')({grid: true})
    ]
}

## script
postcss input.css -o output.css
