### ISSUE TITLE
Custom file extension for dir

### ISSUE THREAD

**Issue by dnepro** [postcss/postcss-cli#21]
I've got a postcss-cli setup where i want all `*.css`-files to be minified (using cssnano) into `filename-as-it-is.min.css` in the same directory without having to specify each file and the according output file on its own, because of the huge amount of files. Is there already a solution i missed out? Otherwise is it possible to include a cli-argument/option to set the file extension, like `--file-extension .min.css` or similar?

By the way, this is the command i run `node_modules/.bin/postcss -u cssnano --dir Web/Resources/Public/Styles/ Web/Resources/Public/Styles/*.css`

With kind regards.

**Comment by RyanZim** [comment]
I don't think there's a way to do this currently. Possibly in the future.
