### ISSUE TITLE
postcss reports plugin missing when it's not

### ISSUE THREAD

**Issue by temaput** [postcss/postcss-cli#214]
Hi! Thats seems odd, but...

My setup is in docker, so everything is global:
`> npm i -g uglify-js postcss postcss-cli cssnano postcss-cssnext autoprefixer babel-core babel-cli babel-preset-env `

this command works fine:
`> BROWSERSLIST="last 2 versions,  >1% in RU" postcss styles.css -u postcss-cssnext`

but this command fails:
`> BROWSERSLIST="last 2 versions, not dead, >1% in RU" postcss styles.css -u postcss-cssnext
Plugin Error: Cannot find module 'postcss-cssnext'`

The only difference is BROWSERSLIST parameter "not dead". Error persist when there is dead parameter alone like BROWSERSLIST="dead" or BROWSERSLIST="not dead". Error also persist with cssnano plugin. Error does not persist however with autoprefixer plugin.

**Comment by RyanZim** [comment]
I suspect postcss-cssnext is using an old version of autoprefixer without `dead` support. @jonathantneal?

**Comment by jonathantneal** [comment]
Yes, @RyanZim, postcss-cssnext uses 7x. That is the cause of this issue, not postcss-cli.

If there is to be another release that would resolve this issue, it has some other questions it must answer tangental to this issue, such as; 1. Should some/all plugins be updated? 2. Should Node v4 be dropped? And 3. Should its dependencies be swapped for postcss-preset-env?

Doing all of these might set us up best for the future. However, doing even parts of 1 and 3 would break promises seen on the homepage. And while 2 means postcss-cssnext tests would pass again, it would break parity with PostCSS. Much to decide.

**Comment by RyanZim** [comment]
postcss-cssnext is deprecated; use postcss-preset-env.
