### ISSUE TITLE
watch mode generates empty files

### ISSUE THREAD

**Issue by mdmoreau** [postcss/postcss-cli#215]
Running postcss-cli 5.0.0 I'm pretty frequently having empty files generated when using watch mode. It's  inconsistent, but sounds exactly like https://github.com/postcss/postcss-cli/issues/87 and similar to https://github.com/babel/babel/issues/4332. I'm seeing the issue on Ubuntu Atom/VS Code like others there mentioned, so maybe it's related to running on Linux.

Locally I've added the lines from https://github.com/babel/babel/blob/ab62a9439918edf97eeea730a444a622542696ff/packages/babel-cli/src/babel/dir.js#L152-L155 to the index.js chokidar options after reading through the babel thread. Since doing that I haven't had the issue occur at all in the several projects where I've made the change.

The npm script I'm using is the following if it helps at all:

`postcss src/css/*.css --dir dist/css --ext .min.css --config config/postcss.config.js --no-map --verbose --watch`

I've also noticed that the same thing happens when the input is a single file instead of a glob. I think I first noticed this behavior at least a year ago, but ended up switching over to webpack shortly after. If there's any other information I can provide to help make things easier, please let me know. Really appreciate all of the work on this!

**Comment by RyanZim** [comment]
Sorry for the slow response, PR welcome.
