### ISSUE TITLE
Warn about no config or empty plugins

### ISSUE THREAD

**Issue by ai** [postcss/postcss-cli#225]
To bring a better onboard experience we should warn about the wrong config on:

1. No plugins are selected
2. Parser === stringifier

I found a case in PostCSS gitter chat when the user was confused.

**Comment by RyanZim** [comment]
Yeah, good point. PR welcome (or I'll probably get to it sometime). Shouldn't warn unless both conditions are true, because they might be transpiling `.sss` to `.css`.

**Comment by ai** [comment]
Yeap, perfect task for junior developers.

I will send developers from Evil Martian’s Cult of Martians.

**Comment by ai** [comment]
Hm. I will do it in PostCSS core.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss/commit/049d3fbfd1c0bcc1b94d8503f48f22d60613a3fe

**Comment by ai** [comment]
Will be released in PostCSS 7
