### ISSUE TITLE
wrong number of output bundles with postcss-import

### ISSUE THREAD

**Issue by htor** [postcss/postcss-cli#227]
i'm having trouble getting `postcss-cli` to output separate bundles for all input css file whenever i use `postcss-import`. they are somehow not processed, or skipped:

```
$ grep postcss-cli package.json 
    "postcss-cli": "^5.0.0",
$ postcss styles/*.css -u postcss-import -u postcss-cssnext -d public/styles
$ ls public/styles/
viewports.css websites.css
$ ls styles/
common.css     home.css       share.css      stream.css     typography.css viewports.css  websites.css
```
content of styles/*.css: https://pastebin.com/82d9xW1D

to me it looks like the two last files in the glob pattern are used as output:
<code>
$ echo styles/*.css
styles/common.css styles/home.css styles/share.css styles/stream.css styles/typography.css <strong>styles/viewports.css styles/websites.css</strong>
</code>

**Comment by RyanZim** [comment]
Try quoting your glob pattern.

**Comment by htor** [comment]
no success single or double quoting the pattern either:

```
$ ls styles/
common.css     home.css       share.css      stream.css     typography.css viewports.css  websites.css 
$ ./node_modules/postcss-cli/bin/postcss "styles/*.css" -u postcss-import -u postcss-cssnext -d public/styles
$ ls public/styles/
viewports.css websites.css
$ ./node_modules/postcss-cli/bin/postcss 'styles/*.css' -u postcss-import -u postcss-cssnext -d public/styles
$ ls public/styles/
viewports.css websites.css
```

**Comment by htor** [comment]
if i drop `postcss-import` from the plugins, all files being processed and copied, but now `@import`s are not processed. so it really looks like this plugin is causing it to happen.

```
$ ls public/styles/
$ ./node_modules/postcss-cli/bin/postcss styles/*.css -u postcss-cssnext -d public/styles

11:5	⚠  Missing @custom-media definition for '--huge-viewport'. The entire rule has been removed from the output. [postcss-custom-media]


13:1	⚠  Missing @custom-media definition for '--small-viewport'. The entire rule has been removed from the output. [postcss-custom-media]

$ ls public/styles/
common.css     home.css       share.css      stream.css     typography.css viewports.css  websites.css
$ 
```

**Comment by RyanZim** [comment]
@htor This is super weird. Please make a reduced test case repo, post it to GH, & send me the link.

**Comment by htor** [comment]
done. git clone this and test it out: 
https://github.com/htor/postcss-import-super-weird

**Comment by RyanZim** [comment]
Honestly, I probably won't get a chance to try this until next week. Sorry, it's just a fact of my current workload.

**Comment by RyanZim** [comment]
I tested your repo, the problem only exists with that `package-lock.json`; delete it and node modules, then reinstall, and you should be good to go!

**Comment by htor** [comment]
yes, that's what i did (did you read my comment?) maybe it's worth looking into why this module is fragile in case other people happen to have the same deps in their project? cheers

**Comment by RyanZim** [comment]
I have no idea how you got your `package-lock.json` into that state, it could even be a problem with npm, IDK. If you can figure out what the problem is and submit a PR, fine. As an open-source maintainer who is not paid for any of my work here, I do not have time to look into issues that aren't reproducible on fresh installs.
