### ISSUE TITLE
Use PostCSS 7

### ISSUE THREAD

**Issue by ai** [postcss/postcss-cli#228]
There are no real breaking changes, we just dropped Node.js 4

**Comment by RyanZim** [comment]
:tada: So happy for this. I'll try to get a new version out ASAP, but it might be the end of this week until I get it done, since there's a software release at work on Thursday.

**Comment by RyanZim** [comment]
Fixed by https://github.com/postcss/postcss-cli/pull/229; will release as soon as I can.
