### ISSUE TITLE
No way to pass the false boolean value for a plugin option using CLI arguments

### ISSUE THREAD

**Issue by sgtpep** [postcss/postcss-cli#23]
I'd like to pass `autoprefixer.cascade=false`. Nothing below works:
```
postcss -u autoprefixer --autoprefixer.cascade=
postcss -u autoprefixer --autoprefixer.cascade=0
postcss -u autoprefixer --autoprefixer.cascade=false
```

**Comment by VinSpee** [comment]
im not certain that setting options works at all… any luck setting anything at all @sgtpep?

**Comment by sgtpep** [comment]
@VinSpee --autoprefixer.browsers="> 0%" works fine, for example.

**Comment by pirxpilot** [comment]
Try: `--no-autoprefixer.cascade`
See: https://github.com/code42day/postcss-cli/issues/48

**Comment by sgtpep** [comment]
@pirxpilot Thank you! It quite counter-intuitive and undocumented, but it works.

**Comment by pirxpilot** [comment]
I [documented it in postcss-cli-simple some time ago][1]
@watilde - may be you can add this (or similar) verbiage to Readme

[1]: https://github.com/code42day/postcss-cli/commit/86a1189c688eea156edf69b4e1a745a38126c89c
