### ISSUE TITLE
Automatically insert postcss- prefix if absent

### ISSUE THREAD

**Issue by danielbayley** [postcss/postcss-cli#24]
Given `postcss-syntax` or `postcss-plugin` you could simply do `postcss -s syntax -u plugin` for example.

**Comment by RyanZim** [comment]
What about plugins like https://github.com/ben-eb/cssnano that don't have a `postcss-` prefix? We would need some sort of trial-and-error logic for this.

**Comment by ben-eb** [comment]
That's possible with https://github.com/shinnn/is-resolvable.

**Comment by RyanZim** [comment]
@ben-eb Thanks for pointing that out.

Implementing this for `--use` wouldn't be too hard, but allowing that syntax in the `postcss.config.js` would require changes to https://github.com/michael-ciniawsky/postcss-load-config. Not sure if I want to support this.

**Comment by RyanZim** [comment]
Sorry, I don't think we're going to support this.
