### ISSUE TITLE
Errors during plugin require() are masked

### ISSUE THREAD

**Issue by eemeli** [postcss/postcss-cli#242]
When a plugin throws an error when it's required, postcss-cli always prints `Plugin Error: Cannot find module '${plugin}'` rather than reporting the actual error.

I spent a little while today debugging because of this, as I was getting the above error due to cssnano throwing a BrowserslistError due to a bad config. That root cause would have been significantly easier to figure out if the original error had not been masked.

**Comment by RyanZim** [comment]
Good point; PR welcome to include the actual error in the error message.
