### ISSUE TITLE
postcss cli binary

### ISSUE THREAD

**Issue by ASVBPREAUBV** [postcss/postcss-cli#252]
Hello,
i really like postcss. i would like to use it outside a node-env.
Could you release binaries?
i dont know if this is even possible with node-modules.

**Comment by RyanZim** [comment]
It's technically possible to make binaries with some external tools, but postcss requires plugins to run, which will require Node, so this isn't practically possible; sorry.

**Comment by ASVBPREAUBV** [comment]
Understandable. Thanks for the fast feedback
