### ISSUE TITLE
v6.1.0 prints empty lines

### ISSUE THREAD

**Issue by XhmikosR** [postcss/postcss-cli#256]
This is a regression of #244.

With 6.1.0: https://travis-ci.org/twbs/bootstrap/jobs/475278409#L666-L695
With 6.0.1: https://travis-ci.org/twbs/bootstrap/jobs/475230811

It seems to me there must be a check before `console.warn`.

**Comment by RyanZim** [comment]
Good catch; why didn't I think of that?
