### ISSUE TITLE
Why can't `from` and `to` be used if input/output are not specified

### ISSUE THREAD

**Issue by BrandonOCasey** [postcss/postcss-cli#259]
It seems a bit weird that the only way to pass `to` and `from` are via command line options. Is there a specific reason that it needs to be done like this? For the projects that I work on it would be much cleaner if we could just pass a config that has `to` and `from` in it.

**Comment by RyanZim** [comment]
It's because the config file has to be looked up relative to the input file. We can't find the config file without knowing the input.

**Comment by BrandonOCasey** [comment]
What if the config file was passed in directly?

**Comment by RyanZim** [comment]
That's not how postcss-load-config works, unfortunately.
