### ISSUE TITLE
Watch config file

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#26]
Currently when the `-w` & `-c` options are specified, postcss rebuilds the css files only when the input file changes (and does not reload the config file). If you change the config file, you need to cancel the process and re-run it.

This is irritating for me since I call postcss from an npm script that starts a dev server, my browser, etc. This script takes a bit of time to start or cancel, so I waste a lot of time when changing the config file. :hourglass: 

I think that when both the the `-w` & `-c` options are specified, postcss should reload the config and rebuild the css when a change is detected in the config file.

I'm not sure if I can submit a PR or not. (I'm extra busy right now)

**Comment by RyanZim** [comment]
@watilde Is this something you would consider?

**Comment by RyanZim** [comment]
@pirxpilot Is this something you would consider?

**Comment by RyanZim** [comment]
@pirxpilot, @watilde bump.

I'm currently wrapping postcss with chokidar-cli as a workaround.

**Comment by RyanZim** [comment]
@pirxpilot @watilde @ai bump, bump, bump.

**Comment by watilde** [comment]
Oops so sorry for my late response. Let me check it.

**Comment by watilde** [comment]
Thanks for the feature request. I agreed with this! I will try to create a patch and also let me keep the thing it's still `patch-welcome` as well.

**Comment by RyanZim** [comment]
@watilde Currently there's no good way to do this with yargs. Let's put this on hold until https://github.com/yargs/yargs/issues/585 is resolved.

**Comment by RyanZim** [comment]
We will be supporting the common config in v3, which should allow us to do this, so adding this issue to the v3 milestone.

**Comment by michael-ciniawsky** [comment]
@RyanZim Seems to be trickier then I thought 😛 , do you have started anything in this regard already?

**Comment by RyanZim** [comment]
@michael-ciniawsky I'll hit this asap.

**Comment by michael-ciniawsky** [comment]
I played around with declaring a variable in global scope assigning the `config.file` `configFile = arr[1].file` to, but adding it to `watcher.watch([ input, configFile ])` doesn't work because of watcher logic . The question is how to trigger a rebuild of all files, but tbh I didn't check chokidar docs for all possible optons until now.

**Comment by RyanZim** [comment]
Don't worry, I'll get it.

**Comment by michael-ciniawsky** [comment]
@RyanZim fixed via #69
