### ISSUE TITLE
Ignore css files from node_modules

### ISSUE THREAD

**Issue by Diokuz** [postcss/postcss-cli#263]
Hi there)

I have a monorepo (yarn workspaces), and my build process includes this stage:

```
yarn postcss "packages/**/*.css" -d lib --base src --config ./postcss.config.js
```

So, all css files from `packages` goes to `lib` folder with the same structure. But, I have a problem: because of `packages/**/*.css` wildward, postcss-cli also copies all css files from corresponding node_modules.

For example:

```
node_modules/
  ...
packages/
  my-awesome-package/
    styles.css
    more-styles/
      some.css
    node_modules/
      some-dep/
        some-styles.css
```

results in

```
lib/
  my-awesome-package/
    styles.css
    more-styles/
      some.css
    node_modules/
      some-dep/
        some-styles.css
```

How to tell postcss-cli do not copy css files from node_modules?

**Comment by RyanZim** [comment]
Try `packages/!(node_modules)/*.css`

Also, no need to pass the `--config` option; postcss-cli will find your config itself.

**Comment by Diokuz** [comment]
`packages/*/*/!(node_modules)/**/*.css` in my case. But what if I have different nesting? E.g. `packages/block/node_modules` and `packages/some/folder/block2/node_modules`? How to exclude node_modules from any level?

**Comment by Diokuz** [comment]
Actually `packages/!(node_modules)/*.css` does not work for css files inside `packages` folder.

**Comment by RyanZim** [comment]
Hmm, I'm thinking you might be better off using an external tool like unix `find` to run `postcss-cli` in your case.

One possible (semver-major) change postcss-cli could make would be to ignore files in the `.gitignore`, using https://github.com/sindresorhus/globby#gitignore.

**Comment by Diokuz** [comment]
`yarn postcss $(find . -name *.css -not -path "*node_modules*") ...` works for me

**Comment by jared-hexagon** [comment]
> yarn postcss $(find . -name *.css -not -path "*node_modules*") -d lib --base src works for me

Unfortunately that is unix only

**Comment by sirtawast** [comment]
> > yarn postcss $(find . -name *.css -not -path "_node_modules_") -d lib --base src works for me
> 
> Unfortunately that is unix only

`find ./src -name "*.css" -not -name "*.min.css"` works for me using `Git Bash` CLI from Git for Windows. Be sure to double quote the * wildcards on Windows!

**Comment by sirtawast** [comment]
> > yarn postcss $(find . -name *.css -not -path "_node_modules_") -d lib --base src works for me
> 
> Unfortunately that is unix only

This seems to work for me using `Hyper` and `Git Bash` from Git for Windows.
```
export CSS_FILES=$(find ./src -name "*.css" -not -name "*.min.css")
```
