### ISSUE TITLE
postcss --replace truncates file to zero bytes when run in "docker build"

### ISSUE THREAD

**Issue by mbrock** [postcss/postcss-cli#268]
Here's my example `Dockerfile`:

```
FROM node:8
WORKDIR /
RUN npm install --quiet postcss-cli@6.1.1
RUN echo "body { color: blue }" > index.css
RUN /node_modules/.bin/postcss *.css --verbose
RUN echo >&2 "Note the valid CSS output without --replace."
RUN /node_modules/.bin/postcss *.css --verbose --replace
RUN >&2 ls -l *.css
RUN >&2 echo "Note the invalid zero-byte output with --replace."
```

And some abridged output of `docker build --no-cache .`:

```
Step 8/9 : RUN >&2 ls -l *.css
 ---> Running in 9432f18a8703
-rw-r--r-- 1 root root 0 Jan 21 11:56 index.css
```

**Comment by mbrock** [comment]
When I try doing the same with but in a `docker run` then I don't get this problem.

I would like to debug it with `strace`, but I don't think there's any way to use `strace` in `docker build`, except maybe on Windows for some reason.

**Comment by RyanZim** [comment]
Unfortunately, there's really no way we can debug this. If you find the problem, patches are welcome, though.
