### ISSUE TITLE
Allow multiple input files w/ output to stdout

### ISSUE THREAD

**Issue by nwmcsween** [postcss/postcss-cli#27]
It would be nice to do postcss file1 file2 file3 file4 with output to stdout if -o isn't specified.

**Comment by RyanZim** [comment]
I would consider this for the future; It probably won't happen anytime soon, though.

**Comment by RyanZim** [comment]
@nwmcsween Why not this?

    cat file1.css file2.css > postcss

**Comment by vphantom** [comment]
@RyanZim Wouldn't that break source map references?

**Comment by RyanZim** [comment]
The more I think about this, the less I like it. Order matters in CSS; concating files in a random order isn't really a good idea. Also have no idea precisely how you could ever keep correct sourcemaps here, so we'd be no better than `cat file1.css file2.css > postcss`. Closing.
