### ISSUE TITLE
Having a `.css` in the directory path breaks external source map paths

### ISSUE THREAD

**Issue by bcomnes** [postcss/postcss-cli#283]
Just ran into a head scratcher: if you are working in a directory path that contains a `.css` in it, source maps are created in the wrong location.

postcss.config.js
```js
module.exports = (ctx) => ({
  map: { inline: false }
})
```

Working directory: `/foo/bar/baz.css/`

Command: `postcss ./index.css -o ./dist/site.css`

Creates `/foo/bar/baz.css/dist/site.css`
and
`/foo/bar/baz.css.map/dist/site.css` (except this is the source map)

I would expect the following files to be created instead:

`/foo/bar/baz.css/dist/site.css`
`/foo/bar/baz.css/dist/site.css.map`

**Comment by RyanZim** [comment]
Yeah, that's a bug. PR welcome to fix it.

**Comment by bcomnes** [comment]
I’ll try to take a look soonish.
