### ISSUE TITLE
Help: No longer found globally installed plugins

### ISSUE THREAD

**Issue by zmni** [postcss/postcss-cli#285]
So, I'm resuming my weekend hobby work after very long break. Update everything to the latest, and then I got this error: 

`Error: Loading PostCSS Plugin failed: Cannot find module 'plugin-name'`.

I installed everything globally: `npm i -g ...`, it's really simple setup.

**package.json**
```json
{
  "scripts": {
    "build": "postcss input.css -o output.css"
  }
}
```

**.postcssrc.json**
```json
{
  "map": false,
  "plugins": {
    "postcss-import": {},
    "postcss-preset-env": {},
    "cssnano": {
      "options": {
        "safe": false
      },
      "autoprefixer": {
        "add": true
      },
      "discardComments": {
        "removeAll": true
      }
    }
  }
}
```

What changed? It used to work without problem. I've tried to search, but I couldn't find anything. Only this very same [stackoverflow question](https://stackoverflow.com/q/44295814) but unfortunately there is no answer.

Anyone can help me? Thank you.

**Comment by RyanZim** [comment]
Installing things globally is a bad practice; you should install everything locally, especially when you're already using an npm script.

**Comment by zmni** [comment]
Thanks for the advice.

So, it's impossible to make it load global plugins? Can you tell me the latest postcss-cli version that stil uses the old behaviour?

**Comment by RyanZim** [comment]
TBH, I never knew it even supported loading global plugins.

**Comment by zmni** [comment]
I just downgrade to `v5.0.1`, and I can confirm, this is the last version that can still load global plugins. I thought there might be a new option in version 6 to toggle this behaviour. Just a little confused when it suddenly stopped working as usual.

Thanks @RyanZim.
