### ISSUE TITLE
How to pass options when not working with a "project"

### ISSUE THREAD

**Issue by remorse** [postcss/postcss-cli#287]
Hi! I have a comment on a closed question about this, but possibly those aren't being seen.

A lot of what I do with CSS is not really part of a "project" per se -- sometimes, the stuff I'm doing never even winds up on the file system (at least, not for a long time), or is inline CSS, or SCSS that I then compile into CSS without saving the SCSS.

I can use postcss-cli to run the text through STDIN and STDOUT, so I can easily add it to my editor as a filter, but there is no way to pass options to any plugins without a config file. But in a lot of cases, there is no good place to put a config file. How am I supposed to do this?

**Comment by RyanZim** [comment]
Answered here: https://github.com/postcss/postcss-cli/issues/144#issuecomment-509683605,. saw that before this. Can continue any discussion here.

**Comment by remorse** [comment]
The primary thing that I want to do is to use something to sort css/scss properties. In particular, I'm looking at the "concentric-css" sorting order. Every tool I can find for that, though, is based on PostCSS. Although PostCSS may be aimed primarily at projects, almost every web search I do now to find sorters (or pretty printers, etc.) winds up at a postcss plugin. It seems, at least in my searching, to have taken over the entire "market". Regardless of where PostCSS is aimed, it is (for my uses) the only game in town, which makes it very annoying that there is no good way to use it.

I don't know what the best answer would be -- postcss-cli-simple has a solution for passing options, but it won't work with STDIN and STDOUT. Is there a magic environment variable that could be read from? A hidden option to specify the configuration JSON blob on the command line?

**Comment by RyanZim** [comment]
postcss-cli actually doesn't even handle reading the config file; configuration is done by postcss-load-config, which is the unified standard for most postcss tools. Not sure how we could read JSON from the command line.

**Comment by remorse** [comment]
Hm. I guess I will post a question/comment over there.

My thought about reading JSON from the command line was that, since JSON is text, there could be a parameter -- say, 'plugin-options' -- the text of which would be JSON text, which would contain something similar to whatever is in the config file.
