### ISSUE TITLE
using postcss with ci/pkg

### ISSUE THREAD

**Issue by feamsr00** [postcss/postcss-cli#288]
Hi There,

I'm hoping to use https://github.com/zeit/pkg to package postcss-cli as a standalone executable. I hate to ask such a basic question, but I'm not quite sure how to configure this project to allow me to build this. Thoughts to what my first steps should be?

Thanks in advance!

**Comment by RyanZim** [comment]
Honestly, I have no experience with `pkg`, so I can't really help you here. If you get it figured out, would love to know about it.

**Comment by feamsr00** [comment]
Fair enough! If I get it working I'll update this issue. I'll try it out within the next week.

**Comment by RyanZim** [comment]
Closing for lack of updates.
