### ISSUE TITLE
Setting cli options from config file.

### ISSUE THREAD

**Issue by dyllandry** [postcss/postcss-cli#289]
I'd like to set my processed file's extensions to `.css` from `.pcss`. This is usually done with the cli `--ext` option. However, I am using [Hugo's](https://gohugo.io/hugo-pipes/postcss/) postcss pipe, and the postcss-cli is not exposed to me. I can, though, set a `postcss.config.js` file.

Is there a way to set the `--ext` option, or achieve a similar end result, solely from a postcss config file?

**Comment by RyanZim** [comment]
Not sure, this would be a question for Hugo
