### ISSUE TITLE
Error: Cannot find module 'autprefixer'

### ISSUE THREAD

**Issue by dwilt** [postcss/postcss-cli#29]
Trying to run a basic command here. I `npm install`ed `autoprefixer` and am trying to run: `postcss -c options.json -o css/test.css test.css`

```json
{
  "use": [
    "autprefixer"
  ]
}
```

I can see `autoprefixer` in the `node_modules` folder and I have a `test.css` file in the root:

```css
body {
    display: flex;
}
```

**Comment by ben-eb** [comment]
You're missing an `o`. 😉

**Comment by pirxpilot** [comment]
If you installed `postcss-cli` globally and `autoprefixer` locally you need [`--local-plugins`][1]

[1]: https://github.com/postcss/postcss-cli#--local-plugins

**Comment by dwilt** [comment]
That was it, thanks!
