### ISSUE TITLE
Command no found

### ISSUE THREAD

**Issue by cpdtzy** [postcss/postcss-cli#291]
I had installed postcss-cli on location direction.
```
npm i -D --save-dev postcss-cli
```
But when I use the postcss.
It was said command not found.

**Comment by RyanZim** [comment]
Are you running it in an npm script, or just on the command line? Installing it locally won't make it available on the command line, you need to run `npx postcss` to access it on the command line.

**Comment by siddsarkar** [comment]
@RyanZim  global install doesnt work too, npx works though. how do we access without npx

**Comment by RyanZim** [comment]
@siddsarkar Please open a new issue with full details instead of bumping old issues.
