### ISSUE TITLE
A new 'official' fork calls for new maintainers

### ISSUE THREAD

**Issue by Siilwyn** [postcss/postcss-cli#3]
## Intro

PostCSS is a tool for transforming styles with JS plugins. These plugins can lint your CSS, support variables and mixins, transpile future CSS syntax, inline images, and more.
## Opportunity

Now that the CLI implementation of PostCSS has moved under the PostCSS organisation on GitHub and people talking about what postcss-cli should become I think the time is there to get a group of people together to maintain and potentially rewrite the code.
## Let's get going

Interested in helping? Reply below with what you want to help with!

**Comment by corysimmons** [comment]
I'm pretty garbage at Node. I'm working on it (for real), but I'm probably not super suited to develop a big project like this.

That said, if no one else steps up to develop it I will.

I can help with getting tasks organized, writing nice docs, and making sure all the code is well formatted/standardized.

That said, I think we should definitely rewrite this from scratch. In which case we'd want to get rid of the "forked from code42day/postcss-cli" so @ai would probably need to make another repo (e.g. `postcss-cli-dev`) for us to work on while this one remains up.

Then when the new CLI is done, we should rename this repo to something like `postcss-cli-legacy` and rename `postcss-cli-dev` to `postcss-cli`.

**Comment by Siilwyn** [comment]
@corysimmons That sounds like a good idea, I'm interested in working on it too. We can start by making a list of what tools & modules we're going to use and how the API should behave.

**Comment by corysimmons** [comment]
I think we should use [Meow](https://github.com/sindresorhus/meow) and we're getting close on deciding on an API in [this issue](https://github.com/postcss/postcss-cli/issues/1).

**Comment by grantcarthew** [comment]
Hi @Siilwyn, I would like to help. See  [issue#9](https://github.com/postcss/postcss-cli/issues/9).

**Comment by watilde** [comment]
:raising_hand: I'm happy to support this. I really like cli projects written in Node.js.

**Comment by pirxpilot** [comment]
Great. I [was hoping someone would volunteer][1]. It makes me sad seeing PRs starting to pile up here.
I liked that you added test in your PR and unless I hear otherwise from @ai I will add you to the project.
I take it you're [watilde] on npm?

[1]: https://github.com/postcss/postcss/issues/154#issuecomment-177278640
[watilde]: https://www.npmjs.com/~watilde

**Comment by watilde** [comment]
Sounds nice! Yes that's me you took, I'm same id on npm as well :blush:

**Comment by Siilwyn** [comment]
I can help with reviewing & merging the pull requests.

**Comment by pirxpilot** [comment]
Didn't hear anyone objecting so I added @watilde to project owners.
Ping me if you have any questions or if you're missing any access rights to update and release postcss-cli.

**Comment by watilde** [comment]
@pirxpilot Could you add me to the [postcss orgs](https://github.com/postcss) as well? I have a plan to integrate [greenkeeper](https://greenkeeper.io/) into this project.

**Comment by ai** [comment]
I can add you to org. But please remind me, if I will not do it in few 2 days (I will hard travel to Iran abd could forget)

**Comment by watilde** [comment]
Ok, sure thing! Take your time and please have fun on your trip ✈️

**Comment by pirxpilot** [comment]
Normally I wouldn't do that but since @ai OKed the idea here, I have sent an org invite to @watilde
Looks like you can use your new acquired super-powers to close this issue BTW ;-)

**Comment by rafaelrinaldi** [comment]
I can also help reviewing PRs and whatever else is needed.

**Comment by grantcarthew** [comment]
I'm also happy to be involved.

**Comment by watilde** [comment]
Since I couldn't make enough time recently, let me ask about a possibility to have a new maintainer in this repository, that I hope it's good for this community. Of course, I'd love to support.

I'd recommend @RyanZim if he has an interest because you could see how he is contributing to the community.

**Comment by RyanZim** [comment]
@watilde: Glad to know you like the idea of me maintaining postcss-cli. @ben-eb added me as a collaborator yesterday, and I am begining to work as a new maintainer. See https://github.com/postcss/postcss-cli/issues/51.

**Comment by RyanZim** [comment]
Going to close this since I am now active maintainer, and v3 is a WIP.
