### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by 4096void** [postcss/postcss-cli#32]
![image](https://cloud.githubusercontent.com/assets/11892251/16446245/490bc560-3e19-11e6-9886-319b2f1b5651.png)
![image](https://cloud.githubusercontent.com/assets/11892251/16446256/5104e29c-3e19-11e6-94a1-0b1a8f7e37aa.png)
my log msg...

**Comment by watilde** [comment]
Hello! Thanks for reporting this. Could you let me know the versions of npm/node you used?
Also, please put your npm-debug.log if you can publish it :)

**Comment by 4096void** [comment]
my mistake, request to close
