### ISSUE TITLE
Skip file write if file content isn't changed

### ISSUE THREAD

**Issue by MartijnCuppens** [postcss/postcss-cli#320]
If the input is the same as the output CSS and the `--replace` flag is passed, the file is always overridden. Can we somehow prevent this from happening? 

The issue I have now is that I have another watcher on these files which detect file changes even if the content is not changed.

https://github.com/postcss/postcss-cli/blob/42fc85e743b20dd8d4f3d6a1d16b4de31f7aa08a/index.js#L222-L227

We could wrap these lines with a simple check to prevent the file write from happening:

```javascript
if (result.css !== css.toString('utf8')) {
  tasks.push(fs.outputFile(options.to, result.css))

  if (result.map) {
    const mapfile = getMapfile(options)
    tasks.push(fs.outputFile(mapfile, result.map))
  }
}
```

Not sure if we can better add a new option or do this check by default, what do you think?

**Comment by RyanZim** [comment]
Don't see a good reason not to do this by default; PR welcome.

**Comment by kentcdodds** [comment]
@MartijnCuppens, I've opened #417 which solves this in a more general way. If I'm not mistaken, what you were asking for is:

> if the input is the same as the output then don't save the file

What I built is:

> if the output is the same as what's currently in the output then don't save the file.

I think what I have in #417 satisfies what you're looking for and solves a significant annoyance for me at the same time :)
