### ISSUE TITLE
Write `.css.d.ts` file if `result.dts` has contents

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-cli#329]
If `result.dts` has contents, please output a `.d.ts` file adjacent to the CSS file.

```js
if (result.dts) {
  tasks.push(fs.outputFile(options.to + '.d.ts', result.dts));
}
```

**Comment by RyanZim** [comment]
How does the `result.dts` property get created? Not seeing it in the docs; just trying to understand the pipeline here.

**Comment by jedmao** [comment]
It's not in the docs. I have a closed source plugin that assigns a string to this property, but really anyone should be able to assign type definitions to a CSS file (or any file for that matter).

I can tell you that if you `import type Foo from './foo.css` and there is an adjacent file named `./foo.css.d.ts` that TypeScript picks it up and that's exactly what I need.

**Comment by RyanZim** [comment]
Closing, since this is non-standard.
