### ISSUE TITLE
Unexpected token { in 7.1.1

### ISSUE THREAD

**Issue by LinAGKar** [postcss/postcss-cli#330]
When trying to do anything with postcss-cli 7.1.1, it fails with `Unexpected token {`. This happens even if the input file is empty, so the problem is not with the input. 7.1.0 seems to work correctly.

**Comment by justindmyers** [comment]
Can confirm the same issue.

Brand new postcss installation in a project, no plugins. Running postcss, even with no options, throw that error in command line.

Version 7.1.0 on the left, 7.1.1 on the right.

![Annotation 2020-07-06 175025](https://user-images.githubusercontent.com/58646/86661309-32c35480-bfb1-11ea-9cb4-c909593adfb0.png)

**Comment by RyanZim** [comment]
Oh, this is a JS syntax error, not a CSS error. `postcss-cli` requires Node 10+; you must be on an earlier version. We officially dropped support for old versions in 7.0.0, but 7.1.1 updated a dependency that includes modern JS code that requires Node 10+ to run, hence the error.
