### ISSUE TITLE
in monorepo, cli fail to set postconfig custom directory to look for a config file

### ISSUE THREAD

**Issue by huchangfa123** [postcss/postcss-cli#331]
## question
I  created a  monorepo project and  i want to set all package with the same postcss.config , the catalog of project as follow:
![企业微信截图_63c57975-9b67-4dab-bcd0-a2730a8433b7](https://user-images.githubusercontent.com/20489087/90092097-9e3fd500-dd5a-11ea-82ed-c83ef3bf48f4.png)

so , i put a postcss.config in root directory. And  in each package  package.json , i set the cli command as follow:
![企业微信截图_2464cd77-87a4-4329-ae76-51ca629c58e6](https://user-images.githubusercontent.com/20489087/90092200-dba46280-dd5a-11ea-8e97-c64ec36a476a.png)

but it's not  work. After testing, i find "--config" as if can only set the directory in below directory , but not upward.

babel can set the config directory use "--root-mode upward" to find the config file in upward directory, 
I wish this cli  can provide the  same command to work ,  or improve the command "--config" to fixed my question

thanks.

**Comment by RyanZim** [comment]
postcss-cli should be able to find your config without the `--config` option. It checks parent directories up to your user home directory by default. Let me know if that doesn't work.

**Comment by huchangfa123** [comment]
this project is monorepo project.And the postcss config file is in root path. In posscss config , I use mixin plugin . 
![image](https://user-images.githubusercontent.com/20489087/90208736-11f5e680-de1c-11ea-99ed-725687999651.png)


pageTitle packjson as follow:
![企业微信截图_3faa0a72-fc0e-4e0e-ad28-d4f90f14a48a](https://user-images.githubusercontent.com/20489087/90208055-76b04180-de1a-11ea-9832-65c68d639950.png)

the root packjson as follow:
![企业微信截图_8f728b3a-797b-47bd-a321-acf79502573a](https://user-images.githubusercontent.com/20489087/90208315-29809f80-de1b-11ea-854a-ea4f6fa82259.png)
use lerna to build the pakages 

if the postcss config is in root path. when I use mixin in pageTitle.css and build , it's building wrong as follow:
![image](https://user-images.githubusercontent.com/20489087/90208910-95afd300-de1c-11ea-8539-c39bff23ac19.png)

only put the config file into to the same path,  building is success
![image](https://user-images.githubusercontent.com/20489087/90208953-b9731900-de1c-11ea-8db0-12b02d7a840e.png)
![image](https://user-images.githubusercontent.com/20489087/90209149-25558180-de1d-11ea-9248-85b02e231127.png)

but if do this, each package in packages have to add the same config file of postcss. Babel can use "--root-mode upward" to make all pakage use the same config file in root path. So, I wish postcss can do this too. And I tried to use "--config", but failed.   Are there any config can finish this ?

thanks a lot.

**Comment by RyanZim** [comment]
`postcss-cli` is picking up your config alright. If it wasn't, it would error out with a different error. The problem isn't that it's not reading your config, the problem is that `postcss-mixins` can't find where your mixin is defined. I'm not super familiar with `postcss-mixins`, are you passing any options to it? Also, you showed the CSS where you defined your mixin, where is that located? `styles/mixins/style.css`?

**Comment by huchangfa123** [comment]
yes, you're right. In postcss.config:
![image](https://user-images.githubusercontent.com/20489087/90352808-ff2b1e00-e076-11ea-8b3d-309cd99b118e.png)
the relative directory of mixin css should change to '../../styles/mixins', the building will success.
the directory is not relatived with the root path where postcss.config stay, but relatived with the path of pageTitle's package.json.

**Comment by RyanZim** [comment]
It's actually probably relative to the directory that the CLI command is run from, which in your case would be the `pageTitle` directory. If you want to make it absolute, you could set it to `path.join(__dirname, 'styles/mixins')`; that will make it work the same no matter where the command is run.
