### ISSUE TITLE
PostCSS 8 support

### ISSUE THREAD

**Issue by ai** [postcss/postcss-cli#344]
[PostCSS 8.0 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0)

- [ ] Move `postcss` to `peerDependencies`
- [ ] Update install docs
- [ ] Update `postcss` version

**Comment by RyanZim** [comment]
Also:

- [ ] Update https://github.com/postcss/postcss-reporter version
- [ ] Upgrade or migrate away from https://github.com/michael-ciniawsky/postcss-load-config

**Comment by ai** [comment]
@RyanZim I updated `postcss-load-config` to support PostCSS 8 and released in 2.1.1.

Let’s use it to release PostCSS 8 support faster.

**Comment by RyanZim** [comment]
Yep, if `postcss-load-config` is up to date, I'm fine with using it.
