### ISSUE TITLE
Use postcss-load-config 3.0

### ISSUE THREAD

**Issue by ai** [postcss/postcss-cli#352]
We updated `cosmiconfig` and the only breaking change is Node.js >= 10 (which is not a breaking change for this project, since PostCSS 8.0 was already limited Node.js to >= 10).

You can release `postcss-load-config` as a patch release.

**Comment by RyanZim** [comment]
Merged in https://github.com/postcss/postcss-cli/pull/351; will release soon. Technically, this will be a minor release, since adds support for `.cjs` configs.

**Comment by RyanZim** [comment]
This was released in v8.1.0
