### ISSUE TITLE
Can't parse SCSS files due to error

### ISSUE THREAD

**Issue by belyan** [postcss/postcss-cli#371]
I have installed latest version of postcss-cli. When I run ```postcss dist/**/*.scss -r --verbose ``` I get this error:

```
if (shim$1.Parser.looksLikeNumber(arg) &&
TypeError: shim$1.Parser.looksLikeNumber is not a function
```

### Versions
```
"postcss": "8.0.0",
"postcss-cli": "8.3.1",
```

**Comment by RyanZim** [comment]
Please post the full error with stack trace. Also, what's your `postcss-scss` version?

**Comment by RyanZim** [comment]
Closing for lack of response.
