### ISSUE TITLE
Cannot find module 'postcss'

### ISSUE THREAD

**Issue by Hongbusi** [postcss/postcss-cli#373]
npm i postcss postcss-cli -D

execute npm postcss ==> Cannot find module 'postcss'

I want to know why. Thank you~

as follows：

![image](https://user-images.githubusercontent.com/53554371/115415280-5a766700-a229-11eb-8614-db91dc0de717.png)

**Comment by RyanZim** [comment]
You're running postcss directly from the command line, so it's using the globally installed version of postcss-cli. Run it from within an npm script, or use `npx postcss`.
