### ISSUE TITLE
postcss : The term 'postcss' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by Ryan-da-ghost** [postcss/postcss-cli#374]
Hello, I have installed postcss via  npm using `npm i -D postcss postcss-cli`
When i run `postcss --use autoprefixer -o assets/css/main.css assets/css/*.css` It doesn't work and it gives me an error! No matter what i do i still get this, i tried removing it and reinstalling it but it doesn't work! Please help!!!

I FORGOT TO MENTION: 
I did run `npm i postcss`

**Comment by RyanZim** [comment]
Installing it locally to your project does not make it globally available. Either run `npx postcss ...` from within your project directory, or put your postcss call in an npm script.

**Comment by Ryan-da-ghost** [comment]
> 
> 
> Installing it locally to your project does not make it globally available. Either run `npx postcss ...` from within your project directory, or put your postcss call in an npm script.

Thanks for all the help ! After LOOKING at the internet for 2-3 hours, i found out the command i should use. it ain't npx but thnx!
