### ISSUE TITLE
postcss-cli 9.0.0 doesn't contain bin folder

### ISSUE THREAD

**Issue by rpokrovskij** [postcss/postcss-cli#403]
It looks like new release 9.0.0 doesn't contain bin folder:

after `npm install`

![image](https://user-images.githubusercontent.com/11598038/134969176-d5c7a675-2654-4869-a9c2-cfbc23a0e03a.png)

**Comment by RyanZim** [comment]
This is intentional; the cli file is now `./index.js`, as noted in the package.json

**Comment by rpokrovskij** [comment]
then remove `bin` from `files` of package.json

**Comment by RyanZim** [comment]
Good catch; done: https://github.com/postcss/postcss-cli/commit/96a7dc67f1ea8f26f1be0261e273dc1c8b925728.
