### ISSUE TITLE
How to call cli with file config?

### ISSUE THREAD

**Issue by HypeNeutron** [postcss/postcss-cli#407]
### in it I mention that from my autoprefixer plugin problem complaint in SASS compiler indent problem in
`sass --style=compressed` 

### This is my CLI
`postcss --use autoprefixer -b 'last 5 versions' assets/css/main.comp.css -o assets/css/main.prefix.css`

### This is my config in autoprefixer  I don't know how correctly used  but after created, but it doesn't work
```js
module.exports = {
  plugins: [require('autoprefixer')({ cascade: false })],
};
```

**Comment by RyanZim** [comment]
The `postcss.config.js` will be used automatically. If you have autoprefixer specified in your `postcss.config.js`, you don't need to specify it on the command line.

Also, you'll need to specify your desired browsers someplace else, there is no `-b` option. See https://github.com/postcss/autoprefixer#browsers for options.

**Comment by RyanZim** [comment]
So your CLI command should just be `postcss assets/css/main.comp.css -o assets/css/main.prefix.css`

**Comment by HypeNeutron** [comment]
> 
> 
> So your CLI command should just be `postcss assets/css/main.comp.css -o assets/css/main.prefix.css`

Ok that it work!  But I'm facing another syntax SASS complaint, something else instead 😂 👌
