### ISSUE TITLE
Disconect Fork

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#41]
This was mentioned in #3, but never done.

Reasons:

- Forks do not show in GH search results: https://github.com/search?utf8=%E2%9C%93&q=postcss-cli.
- Contributions to forks are not counted on users profiles.
- A fork doesn't look like it's _"official"_.

IIRC, you need to contact GH support to do this.

CC: @ai @watilde @pirxpilot

**Comment by ai** [comment]
LGTM

**Comment by RyanZim** [comment]
@ai Are you going to do it personally?

**Comment by ai** [comment]
I think origin repo author should ask about it from GH.

**Comment by pirxpilot** [comment]
I wrote to github support to request that. Will keep you posted.

**Comment by pirxpilot** [comment]
Done.
