### ISSUE TITLE
9.0 release

### ISSUE THREAD

**Issue by djibe** [postcss/postcss-cli#410]
Hello,

No 9th version is stated in the Github Releases section (https://github.com/postcss/postcss-cli/releases).

Thanks a lot.

**Comment by RyanZim** [comment]
Yeah, I don't use GitHub Releases here anymore; see the CHANGELOG here: https://github.com/postcss/postcss-cli/blob/master/CHANGELOG.md

**Comment by djibe** [comment]
Sorry about that.
