### ISSUE TITLE
Change filenames for multiple 

### ISSUE THREAD

**Issue by mantismamita** [postcss/postcss-cli#412]
Hello, I was wondering how/if I could change the name of the file once it was genereated. For example:
`postcss src/assets/styles/__global.css -o src/assets/styles/global.css` would change the filename for one file but I am not able to change the filenames for mutiple files with  `postcss src/assets/styles/global/__*.css -d src/assets/styles/global/*.css` I'm getting an error 
```
[Error: ENOTDIR: not a directory, open '/Users/xx/xx/client/src/assets/styles/global/__light.css/__light.css'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'open',
  path: '/Users/xx/xx/client/src/assets/styles/global/__light.css/__light.css'
}
```

**Comment by RyanZim** [comment]
Unfortunately, that's not possible with postcss-cli.

**Comment by mantismamita** [comment]
Ok, cheers for the quick response.
