### ISSUE TITLE
Use existing sourcemaps for .sass

### ISSUE THREAD

**Issue by kkmuffme** [postcss/postcss-cli#422]
I have a hello.sass file, which gets compiled to hello.css with a sourcemap.

When I run postcss to autoprefix, it will generate a new sourcemap, which will break the sourcemap of the sass from working.
Instead I want it to update the existing sourcemap (like "-r" does to the .css file).

I found a solution here https://github.com/postcss/postcss/issues/222 but it's not for CLI and I don't know how I could do this with postcss-cli.

My command:
postcss --config postcss.config.js --use autoprefixer --map -r hello.css

My settings:
postcss.config.js

```
module.exports = ( ctx ) => ({
	plugins: {
		'/usr/lib/node_modules/postcss-sorting': {
			'order': [
				'custom-properties',
				'dollar-variables',
				'at-variables',
				'declarations',
				'at-rules',
				'rules'
			],
			'properties-order': 'alphabetical',
			'unspecified-properties-position': 'bottom'
		}
	}
});
```

**Comment by RyanZim** [comment]
It should automatically pick up the sourcemap, if SASS left the correct sourcemap comment.

Also, you should define all your plugins in config, instead of using `--use`

**Comment by RyanZim** [comment]
Assuming this is resolved.
