### ISSUE TITLE
Report a plugin version from CLI

### ISSUE THREAD

**Issue by ivantcholakov** [postcss/postcss-cli#43]
I call postcss through CLI from PHP code and I use Autoprefix plugin. From command line there is a way postcss version to be reported:

``` sh
postcss --version
```

But I want using postcss from CLI again to query which version of autoprefixer plugin it is going to be used, but likely there is no way.

Could you add such a feature - version reporting for plugins?

**Comment by RyanZim** [comment]
I'll leave the decision to others, but this is a very small edge case IMO.

How would it report multiple plugins?

**Comment by ivantcholakov** [comment]
I don't mind one CLI call for reporting one plugin version. Then I could do several CLI calls if it is necessary. Maybe something like this:

```sh
 postcss --use autoprefixer --version
```

https://www.npmjs.com/package/autoprefixer-cli - this package has the option for version reporting, but in the description it is said:
"The official way to use Autoprefixer is postcss-cli, this tool is for legacy code."

**Comment by RyanZim** [comment]
`postcss --use autoprefixer --version` wouldn't work, the current argument parser doesn't support positional arguments like that IIRC.

What I'm wondering is: couldn't you read the package.json for autoprefixer in node_modules?

**Comment by ivantcholakov** [comment]
This would not be CLI anymore.

**Comment by ivantcholakov** [comment]
A wonder why positioning would be problem, this is fine too:

```sh
postcss --version --use autoprefixer
```

**Comment by RyanZim** [comment]
@watilde @ai Thoughts?

**Comment by ai** [comment]
I don’t think it is a postcss-cli issue. Use npm for it :)
