### ISSUE TITLE
Bundling/concatenation of css files is not allowed? 

### ISSUE THREAD

**Issue by skitsanos** [postcss/postcss-cli#434]
`postcss src/styles/*.css -o dist/lib.css` still firing the error `Input Error: Must use --dir or --replace with multiple input files`

PostCSS does not allow bundling into a single file?

Unfortunately couldn't find anything about it in the documentation...

**Comment by RyanZim** [comment]
No, we cannot concatenate files, because CSS is dependent on order. If you know order does not matter, you can use regular `cat` and pipe to postcss like this: `cat src/styles/*.css | postcss -o dist/lib.css`
