### ISSUE TITLE
Support the common config

### ISSUE THREAD

**Issue by watilde** [postcss/postcss-cli#45]
From this discussion: https://github.com/michael-ciniawsky/postcss-load-config/issues/18. PostCSS will have the common config file via `postcss-load-config` which will potentially be added to the core(or not). Either way, where the loader will be placed, I think it would be great if we could support it at here CLI as well, and also it means the update may make a breaking change.

For a while, we need to wait for new release of the loader to fix a few issues.

**Comment by RyanZim** [comment]
Done in the develop branch.
