### ISSUE TITLE
Something not right with --watch

### ISSUE THREAD

**Issue by manishtpatel** [postcss/postcss-cli#47]
I do following commands to compile from scss to css then apply autoprefixer

`START /B node_modules\.bin\node-sass "src\scss\app.scss" "public\css\app1.css" -w -r --include-path="bower_components\foundation-sites\scss" --include-path="bower_components\motion-ui\src" --source-map=true`

`CALL ./node_modules/.bin/postcss public\css\app1.css -o public\css\app.css --use autoprefixer --autoprefixer.browser "last 2 version, ie >= 11" -w -m`

node-sass works just fine, it picks up changes as expected and output is 100% times fine.

But 1 out of 4 times postcss generates following output 

`/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJhcHAuY3NzIn0= */`

**Looks like postcss-cli watch is not waiting for file commit or something**

**Comment by manishtpatel** [comment]
Looking at chokidar documentation could awaitWriteFinish help?
![capture](https://cloud.githubusercontent.com/assets/249478/20188384/6aef1e52-a746-11e6-8c55-3a95e86306da.PNG)

**Comment by RyanZim** [comment]
@manishtpatel What's the approximate size of `public\css\app1.css`?

**Comment by RyanZim** [comment]
@manishtpatel Strange.

Can you make a reduced test case repo and post it to GitHub so I can try it locally?

The other option would be to try editing https://github.com/postcss/postcss-cli/blob/master/index.js#L157 in your `node_modules` folder to set `awaitWriteFinish: true` and see if that helps.

Another possibility: try using the `--poll` option.

BTW, what's your operating system, node.js version, and postcss-cli version?

**Comment by RyanZim** [comment]
Going to assume this is resolved.
