### ISSUE TITLE
[Qu] Am I attemping to use this correctly?

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-cli#48]
I am trying to `npm run pcss` here: 

https://github.com/quantumjs/solar-popup/blob/master/package.json#L9

But the output file (`foo.css`) just contains the contents of src/index.pcss

Anything you can see I'm doing wrong here?

thanks

**Comment by RyanZim** [comment]
@QuantumInformation You need to specify which plugins to use in your `old.config.json` file:
```
{
  "use": ["postcss-import", "postcss-css-variables", "autoprefixer"],
  "autoprefixer": {
    "browsers": "> 5%"
  }
}
```
Passing empty objects to plugins isn't needed; however, you must list all your plugins in the `use` array in the order you want them applied.

BTW, postcss-cli doesn't support the common config yet; coming in the next major version.

If this fixes your problem (it should), please close this.

**Comment by QuantumInformation** [comment]
Cheers Ryan, thats bure brill!

**Comment by QuantumInformation** [comment]
I'm now getting an error for this config file:

```
{
  "use": ["postcss-smart-import", "postcss-css-variables", "autoprefixer","postcss-nested"],
  "autoprefixer": {
    "browsers": "> 5%"
  }
}
```

the log:

```
Invalid JSON config file: postcss.config.json

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/nikos/.nvm/versions/node/v6.9.1/bin/node" "/Users/nikos/.nvm/versions/node/v6.9.1/bin/npm" "run" "watch-pcss"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! quantumjs@1.0.0 watch-pcss: `postcss -w src/index.pcss  -o build/site.css -c postcss.config.json src/index.pcss `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quantumjs@1.0.0 watch-pcss script 'postcss -w src/index.pcss  -o build/site.css -c postcss.config.json src/index.pcss '.
```

**Comment by QuantumInformation** [comment]
I just tried the old config previously discussed, still same issue.

Using v2.6.0

**Comment by RyanZim** [comment]
@QuantumInformation Strange. Can you create a reduced test case and post it as a gist or repo on GitHub?

**Comment by QuantumInformation** [comment]
ok

**Comment by QuantumInformation** [comment]
@RyanZim I probably made a mistake somewhere so I went the ease route and used the webpack loader to process my postcss. My other postcss-cli project still going good.
