### ISSUE TITLE
Watch mode should produce some console output every time compilation runs

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-cli#49]
ATM nothing is output to the console, would be nice to see success msg.

**Comment by RyanZim** [comment]
:+1: I would agree this would be nice in some cases, especially if your css build takes a while to complete. It would probably be best to include a timestamp in the message.

**Comment by RyanZim** [comment]
@QuantumInformation This will be fixed in v3.

**Comment by QuantumInformation** [comment]
good stuff!

**Comment by RyanZim** [comment]
Closing, will be released in v3.
