### ISSUE TITLE
Is it possible to use --watch and --replace at the same time

### ISSUE THREAD

**Issue by danhayden** [postcss/postcss-cli#5]
I have been attempting to use both of these options at the same time and end up in an endless loop as the watch starts again when it sees the changes from the replace.

**Comment by Grawl** [comment]
:+1: the same problem

**Comment by FND** [comment]
A quick workaround might be to just debounce the event handler:
https://github.com/postcss/postcss-cli/blob/master/index.js#L153

```javascript
watcher.on('change', debounce(100, function() {
  async.forEach(entryPoints, compile, function(err) {
    return onError.call(this, err, true);
  });
}));


// adapted from StuffJS <https://github.com/bengillies/stuff-js>
function debounce(delay, fn) {
  var timer;
  return function() {
    var self = this;
    var args = arguments;
    if(timer) {
      clearTimeout(timer);
      timer = null;
    }
    timer = setTimeout(function() {
      fn.apply(self, args);
      timer = null;
    }, delay);
  };
}
```

That's not a great solution, but might at least unblock you for the moment?

**Comment by danhayden** [comment]
@FND thank you for the suggestion. I forked the repo and implemented the debounce function however seem to be having the same issue. I increased the delay from 100 to 500 and still no luck.

**Comment by FND** [comment]
Can you provide a minimal example (e.g. based on [this one](https://gist.github.com/FND/8334c63229867e33feae)) so I can have a quick look?
