### ISSUE TITLE
v3: --config doesn't work

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#55]
I can't seem to get the `-c|--config` option working on the `develop` branch.

Can't investigate ATM, but this needs fixed or removed before the release.

CC: @michael-ciniawsky

**Comment by michael-ciniawsky** [comment]
We could handle it in the way, if '--use|-u'  config (inline) specified => run without `postcss-load-config` 

```js
if (argv.use) {
  postcss(use.plugins).process...
}

postcssrc(argv.ctx, argv.config).then((config) => postcss(config.plugins).process...)
// argv.config = 'alternativ/path/to/postcss.config.js'
```

**Comment by michael-ciniawsky** [comment]
It doesn't work because I didn't use it until now, it's for the case an alternative config path is needed for `postcss-load-config` to start searching for `postcss.config.js` in separate e.g `./config` folder.

**Comment by RyanZim** [comment]
@michael-ciniawsky 

> it's for the case an alternative config path is needed for postcss-load-config to start searching for postcss.config.js in separate e.g ./config folder.

Is that really a use-case we need to support?

---

> We could handle it in the way, if '--use|-u' config (inline) specified => run without postcss-load-config

That brings up an interesting point, what should the behavior of `--use` be if plugins are specified in the config? Should we entirely bypass the config? The config could still specify parser, etc. @ai Thoughts on this?

**Comment by ai** [comment]
I think `-u` should disable config. Use arguments if you start it :).

**Comment by RyanZim** [comment]
SGTM, just didn't know what to think. BTW, thanks for answering all these quick questions I throw at you. :smile:

**Comment by michael-ciniawsky** [comment]
> Is that really a use-case we need to support?

While I don't use it myself, people started to ask for it @postcss-loader, it's not difficlt to implement just pass `argv.config` as second argument to `postcssrc(ctx, argv.config)`

> That brings up an interesting point, what should the behavior of --use be if plugins are specified in the config? Should we entirely bypass the config? The config could still specify parser, etc. @ai Thoughts on this?

Thats actually the issue with `--ctx|-x` && `--use|u`, we could break the current `-u` behaviour make it the CLI command for working with `ctx` and `postcss.config.js` is mandatory from `v3+` or separate it enterily from `postcss.config.js` stuff for quick usage + a new `--ctx|-x` command.

Create a config when using `--use|u` for the 'first' time and no config found is also an option discussed before, both ways are still kind of unpleasant atm imho.

**Comment by RyanZim** [comment]
@michael-ciniawsky I am strongly opposed to requiring a `postcss.config.js`. That would hurt the following use-cases:

- Using as an autoprefixer CLI: `postcss --use autoprefixer *.css -d build/` (Copied from autoprefixer's docs: https://github.com/postcss/autoprefixer#cli) This might be used by some projects that use sass, less, or stylus, and only use autoprefixer.
- SugarSS compiler: `postcss --parser sugarss *.sss -d build/`

I don't want to break any of those use-cases. Not to mention that it is my go-to tool for quickly testing bug reports.

I think we just need to clearly document that `--use` bypasses the config.

**Comment by michael-ciniawsky** [comment]
@RyanZim That would work as before it just scaffolds a `postcss.config.js`  if none in cwd() found, could be in os.homeDir() and/or even a tempfile then, it's just about the initial use and to get plugin loading logic from `postcss-load-config`, we can of course also bypass it and add new context command. its just the question which approach is easier and introduces lesser bloat.

**Comment by RyanZim** [comment]
@michael-ciniawsky Don't bother writing a file to be loaded by `postcss-load-config`. I'm not sure that it would make it any easier, and that's an extra file read/write. The primary performance bottleneck with anything like this is the file system; we want to optimize this as much as possible.

FYI, I'm in the middle of doing some major refactoring to index.js that should make implementing `--use` much easier.

**Comment by michael-ciniawsky** [comment]
Yep, I/O before processing contents especially when it is for quick access is surely bad.
Ok, let's wait for your `--use` implementation and iterate from there, I will try to find a solution afterwards and we'll see whats possible.

**Comment by RyanZim** [comment]
SGTM

**Comment by RyanZim** [comment]
Another related question for @ai:

Should we allow setting the output file via `options.to` in the postcss config? I'm inclined to say no, since this would introduce complexity.

**Comment by michael-ciniawsky** [comment]
@RyanZim `-c|--config` flag should work similiar to `postcss-cli` =< v2. Given as second argument to postcssrc this overrides the path where it starts searching for `postcss.config.js`. Use(less ;))case we often had requested @postcss-loader is e.g

```
| – config
|    | – postcss.config.js
| – src 
|    | – index.css
|
| – package.json
```

```bash
postcss --config ./config ...
```

**Comment by ai** [comment]
> since this would introduce complexity

In this case, I agree :)

**Comment by ai** [comment]
@michael-ciniawsky maybe we should remove `options.to` from postcss-load-config — nobody use it :D

**Comment by michael-ciniawsky** [comment]
@ai Yep :D, I will test across all build tools when integration is completed and remove it from `postcss-load-config` when no valid usecase found. Build tools should always use their I/O logic if available

**Comment by michael-ciniawsky** [comment]
@RyanZim TL;DR Close

 I 'fixed'  `-c|--config` it in the errors branch, the reason was `yargs.config` expects a valid JSON config (whatever that is). Removing it solved the problem and `argv.config` is just a string passed to `postcss-load-config`.

**Comment by RyanZim** [comment]
@michael-ciniawsky I want to make sure that the v2-related stuff doesn't apply to v3 also, but this is something that should be done.
