### ISSUE TITLE
Don't enforce .css extensions

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#59]
In the v3 code, the output file's extension is coerced to `.css`: https://github.com/postcss/postcss-cli/blob/develop/index.js#L124-L126.

Is that desirable behavior?

CC: @ai

**Comment by ai** [comment]
PostCSS could be used for `.scss` → `.scss` transformation too :(.

**Comment by RyanZim** [comment]
> PostCSS could be used for .scss → .scss transformation too :(.

You're right; I will remove that logic.

**Comment by RyanZim** [comment]
Fixed in dbdc330
