### ISSUE TITLE
Config file format is misdocumented

### ISSUE THREAD

**Issue by wbyoung** [postcss/postcss-cli#64]
I know this probably doesn't matter much since v3 work & #55 probably supersedes it, but the [first two config formats](https://github.com/postcss/postcss-cli/tree/80bf8615cd6f3a98af4200dc7bdd89e4a88d3705#--config-c) don't seem to work, and there also [doesn't seem to be anything](https://github.com/postcss/postcss-cli/blob/80bf8615cd6f3a98af4200dc7bdd89e4a88d3705/index.js#L11-L12) in the current code base to handle them.

I don't know what the timeline is for v3, but if it's a long way off, should the docs be updated to remove those?

**Comment by RyanZim** [comment]
@wbyoung Config file loading is handled by yargs itself. https://github.com/postcss/postcss-cli/blob/80bf8615cd6f3a98af4200dc7bdd89e4a88d3705/index.js#L11 tells yargs to treat that option as a file to load config from.

Usage is `postcss -c postcss.config.json`.

If this doesn't work for you, let me know and I'll reopen.

**Comment by wbyoung** [comment]
@RyanZim right, I understood that's what was happening in the code via `yargs`. The examples still don't work, and there's nothing that would transform those examples (based on the docs of `yargs`) into `use` arguments to be processed by `postcss-cli`.

Example of a JSON file with keys **not working**:

```bash
mkdir test
cd test
npm i --save postcss-cli postcss-modules
echo '.class-name { color: red; }' >> styles.css
echo '{"postcss-modules": {}}' >> postcss.config.json
./node_modules/.bin/postcss -c postcss.config.json styles.css
```

```css
.class-name { color: red; }
```

Example of a JS file with keys **not working**:

```bash
mkdir test
cd test
npm i --save postcss-cli postcss-modules
echo '.class-name { color: red; }' >> styles.css
echo 'module.exports = {"postcss-modules": {}}' >> postcss.config.js
./node_modules/.bin/postcss -c postcss.config.js styles.css
```

```css
.class-name { color: red; }
```

But the final example, the one that `yargs` does support (by adding CLI options) **does work**:

```bash
mkdir test
cd test
npm i --save postcss-cli postcss-modules
echo '.class-name { color: red; }' >> styles.css
echo 'module.exports = {"use": ["postcss-modules"]}' >> postcss.config.js
./node_modules/.bin/postcss -c postcss.config.js styles.css
```

```css
._class-name_wybo3_1 { color: red; }
```

**Comment by RyanZim** [comment]
Docs are a bit unclear.

You still have to specify `use`, a list of plugins to use.

Example:
```
{
    "use": ["autoprefixer", "postcss-cachify"],
    "input": "screen.css",
    "output": "bundle.css",
    "local-plugins": true,
    "autoprefixer": {
        "browsers": "> 5%"
    },
    "postcss-cachify": {
        "baseUrl": "/res"
    }
}
```

The other example configurations would still require doing `postcss -u autoprefixer -c postcss.config.json`.

Given that v3 totally redoes configuration, I don't think I'll bother with the docs for v2.

**Comment by wbyoung** [comment]
Ah, got it. Thanks, @RyanZim.
