### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by michael-ciniawsky** [postcss/postcss-cli#68]
Can someone please enable gh-pages for this repo so the CLI logo is getting displayed correctly?

**Comment by RyanZim** [comment]
Ping @ai, I can't access the settings tab.

**Comment by ai** [comment]
[Done](https://github.com/postcss/postcss-cli/tree/gh-pages). Remove empty `logo.png` before work.

**Comment by RyanZim** [comment]
@michael-ciniawsky I'll finish this job.

**Comment by RyanZim** [comment]
Fixed
