### ISSUE TITLE
PostCSS does not create output directory

### ISSUE THREAD

**Issue by andismith** [postcss/postcss-cli#7]
I'm using postcss-cli (and autoprefixer) with the command:

`postcss --use autoprefixer src/css/*.css --dir dist/css --map --local-plugins`

But it is failing with a ENOENT error as the output directory `dist/css` does not exist (it has been cleaned as part of the build). The input directory `src/css/` does exist. Full error below:

`{ [Error: ENOENT: no such file or directory, open 'dist/css/main.css']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/css/main.css' }`

Is there a way I can get postcss to create this directory before it tries to write to it?

I'm using v2.5.1

Thanks

**Comment by ben-eb** [comment]
```
mkdir -p dist/css && postcss --use autoprefixer src/css/*.css --dir dist/css --map --local-plugins
```

**Comment by andismith** [comment]
Thank you @ben-eb 

So it's intended not to make the directory for you?

**Comment by ben-eb** [comment]
My general opinion on shell tools is less is more, keeps core functionality smaller and easier to reason about. :smile:
