### ISSUE TITLE
--map option

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#70]
What is the optimum usage for the `--map` option?

We need to support inline maps and `filename.css.map` files.

Do we need to support writing the map file to a different filename? I would be inclined to think not.

CC: @ai @michael-ciniawsky

**Comment by michael-ciniawsky** [comment]
In my opinion 'inline' or in 'tandem' with the css file (output/options.to)

**index#processCSS**
```js
if (result.map) fs.outputFile(options.to, JSON.stringify(result.map))
// uncertain of JSON.stringify() is needed :)
```

**Comment by RyanZim** [comment]
Yeah, I think external maps are a good default, how should we allow disabling them or specifying inline maps?

`postcss --map inline ...` & `postcss --map false ...`?

**Comment by ai** [comment]
* inline map by default (already implemented in PostCSS core)
* copy all maps settings if input file contains map (already implemented in PostCSS core)
* allow to save in `INPUT.map` file.
* allow to save in file, but remove `/*= sourceMap…*/` annotation comment.

**Comment by RyanZim** [comment]
@ai OK, any recommendations on the best usage for the command line flag?

**Comment by ai** [comment]
@RyanZim I am not good in CLI arguments design :(. Up to you.

**Comment by michael-ciniawsky** [comment]
```postcss --map false``  No Sourcemap
```postcss --map file || postcss --map 'path/to/file.ext.map'``` // postcss --map file is weird :D

**Comment by ai** [comment]
Also Sass and Uglify could be used as example.

**Comment by michael-ciniawsky** [comment]
mom

**Comment by michael-ciniawsky** [comment]
let's dot it like in gulp :D  

```
postcss in.css -o out.css                       // inline (default)
postcss in.css -o out.css --map false  // none
postcss in.css -o out.css --map '.'       // input.css.map
```

**Comment by RyanZim** [comment]
I don't really like any of the proposals so far. How about splitting it into two flags?
```
postcss in.css -o out.css --disable-map  # none
postcss in.css -o out.css --map-file  # input.css.map
```

**Comment by michael-ciniawsky** [comment]
`--map-disable` for consistency resaons, but `'.'` or `path/where/to/save/file.ext.map` vs. `--map-file` or `--map-file path/../`, note that with two flags we loose shorthand `-m` / get `md`&& `mf` which is unintuitive ihmo.

```
postcss in.css -o out.css --map-disable                          # none
postcss in.css -o out.css --map-file [path/to/save/file.ext.map] # input.css.map
```


```
postcss in.css -o out.css --map false                          # none
postcss in.css -o out.css --map . [path/to/save/file.ext.map]  # input.css.map
```

**Comment by ai** [comment]
`--no-map` is more popular way to disable feature in CLI.

**Comment by michael-ciniawsky** [comment]
Yep `--no-map` and `--map <path>` is another good option

**Comment by RyanZim** [comment]
> Yep --no-map and --map <path> is another good option

:+1: I'm still not sure if we need `--map <path>`, why not make `-m|--map` a boolean flag for external maps?

**Comment by michael-ciniawsky** [comment]
Ok if it is a `{Boolean}` param, `--no-map` / ` --map` is ok , but the shorthands `-m` / `-nm` ? Why not simply 

```js
postcss in.css -o out.css          # Inline [default]
postcss in.css -o out.css -m       # File
postcss in.css -o out.css -m false # None
```

**Comment by RyanZim** [comment]
> --no-map is more popular way to disable feature in CLI.

I wouldn't bother with a shorthand for `--no-map`. `-m` works fine for `--map`.

**Comment by michael-ciniawsky** [comment]
kk so we agreed upon `--map` and `--no-map`? Because I'm on updating the docs 😛

**Comment by RyanZim** [comment]
Yep. Thanks for doing the docs, BTW.

**Comment by RyanZim** [comment]
Done: https://github.com/postcss/postcss-cli/pull/73
