### ISSUE TITLE
postcss-cli do not copy folder structure from input files when pattern is used

### ISSUE THREAD

**Issue by aesopturtle** [postcss/postcss-cli#78]
>Reopened from https://github.com/postcss/postcss/issues/958

I am trying to compile multiple `*.pcss` files and have the `*.css` output sit in the same directory. For example, I have the following structure:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
```
When running:
```
postcss --use precss src/**/*.pcss --dir out/
```
I expect:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
out
-- test1
---- 1.css
-- test2
---- 2.css
-- test3
---- 3.css
```
But what I got is:
```
src
-- test1
---- 1.pcss
-- test2
---- 2.pcss
-- test3
---- 3.pcss
out
-- 1.pcss
-- 2.pcss
-- 3.pcss
```
So there are 2 issues here:
1. The output doesn't have the same folder structure as the input when used with pattern.
2. I don't seem to be able to specify the output file extension when using `--dir`.

Any suggestion please?

By the way, it would be great if such options are also available in a config file as that's where I actually configure the options :)

**Comment by michael-ciniawsky** [comment]
👋  Do you see a red logo when `postcss -v`

**Comment by aesopturtle** [comment]
@michael-ciniawsky Yep. It says 2.6.0.

**Comment by michael-ciniawsky** [comment]
Version printed should still display 2.6.0 since it's not updated yet

**Comment by aesopturtle** [comment]
I see.

**Comment by michael-ciniawsky** [comment]
When you see the red postcss logo you are on v3@beta :) Place the `postcss.config.js` in the root of your project for getting started

**Comment by aesopturtle** [comment]
I tried with just `postcss --use precss src/**/*.pcss --dir out/` but still got `Cannot find module 'src/**/*.pcss'`

**Comment by RyanZim** [comment]
@aesopturtle Try `postcss src/**/*.pcss --use precss --dir out/`

**Comment by aesopturtle** [comment]
@RyanZim That works! :D
But it still doesn't copy the folder structure. All files in subfolders are output under the same folder (`out/`) and the extension remains `pcss`.

**Comment by RyanZim** [comment]
> So there are 2 issues here:
> 
>    1. The output doesn't have the same folder structure as the input when used with pattern.
>    1. I don't seem to be able to specify the output file extension when using --dir.

1. This is a known issue with both v2 & the development version; issue is here: https://github.com/postcss/postcss-cli/issues/30.
1. Opened a new issue for that here: https://github.com/postcss/postcss-cli/issues/79.

**Comment by aesopturtle** [comment]
As far as I remember, if the input has multiple files, either `-d` or `-r` must be specified, right? How about... if `-d` or `-r` is not specified, we output at its own folder?

**Comment by aesopturtle** [comment]
@RyanZim Thanks :)

**Comment by RyanZim** [comment]
> As far as I remember, if the input has multiple files, either -d or -r must be specified, right? How about... if -d or -r is not specified, we output at its own folder?

@aesopturtle Not sure what you mean; what would the files be named?

**Comment by aesopturtle** [comment]
@RyanZim The output file should have the same name but with an extension following `--ext`(?) option.

**Comment by RyanZim** [comment]
Not in favor of that; since the `--ext` option will only be used in a few cases. Also would be confusing upgrading from v2.

**Comment by michael-ciniawsky** [comment]
@ai Are options an the result {Object} ? 
@RyanZim Maybe we can use it for getting the dirname from options.from or otherwise I need to find something else

**Comment by RyanZim** [comment]
@michael-ciniawsky :confused: What are you trying to say?

**Comment by michael-ciniawsky** [comment]
For nested output directory support we need to get the dirname of the src/**/*.css glob => `/**/` somewhere, just thinking out loud where :D at best

**Comment by RyanZim** [comment]
@michael-ciniawsky Here was a PR for v2: https://github.com/postcss/postcss-cli/pull/31. That may give you some ideas.

At any rate, I'm going to close this issue since discussion has moved elsewhere.

@michael-ciniawsky If you want to do more thinking out loud, do it on gitter, there are plenty of helpful people there.
