### ISSUE TITLE
v3 questions

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#83]
Attn: @ai @michael-ciniawsky

Some odds and ends that need answered before v3:

- https://github.com/postcss/postcss-cli#--local-plugins - Do we need this for v3?
- v2 allowed passing options to plugins via the command line (`--plugin.option=value`). IMO this should be in the config file, anyone disagree?

I may ask additional questions later in this thread.

**Comment by michael-ciniawsky** [comment]
1. `--local-plugins`is superseded by `postcss-load-config`
2. Depends it doesn't hurt, personally find it verbose and would avoid it

**Comment by RyanZim** [comment]
@michael-ciniawsky I agree :100:

**Comment by michael-ciniawsky** [comment]
@RyanZim How did v2 handle `postcss -u plugin --plugin.options.key [ options, option ] => {Array}` ?

**Comment by RyanZim** [comment]
v2 usage:

`postcss -u postcss-url --postcss-url.url=copy` would run `postcss-url` with the `url` option set to `copy`.

IIRC, the dot notation was handled by yargs. I'm not anxious to support this in v3.

**Comment by michael-ciniawsky** [comment]
Yep for key values -> `{String}` ok, but if e.g `-u postcss-import --postcss-import.path [Array]`
one would need to repeat `--postcss-import.path 'path'` several times right?

**Comment by RyanZim** [comment]
I dunno, I always used a config file when I needed options.

**Comment by michael-ciniawsky** [comment]
I also never used it, it's not convenient, but maybe for a quick change 

```bash
postcss src/*.css -u autoprefixer --autoprefixer.browsers 'last 2 versions' | cleancss
```

On the other hand `autoprefixer`, `stylelint`  && `cssnano` have ther own CLI's

**Comment by RyanZim** [comment]
Nah, kill it. If people really want it, we can re-add it.

**Comment by michael-ciniawsky** [comment]
Yep, done. The main remaining part is the watcher, but I can push it in it's 'initial state' and you can finally also start working on shaping the edges, bc in the v3 PR I idiotically forgot to checkout a branch 🤕

**Comment by RyanZim** [comment]
@michael-ciniawsky Should we support `--map`/`--no-map` overriding `postcss.config.js`?

**Comment by michael-ciniawsky** [comment]
@RyanZim It doeslike that atm


```bash
postcss -m 
```

**postcss.config.js**
```js
module.exports = (ctx) => ({
  map: ctx.options.map || { inline: true } // set map from CLI or fallback
})
```

**Comment by RyanZim** [comment]
I meant: 

    postcss -m 

**postcss.config.js**

```
module.exports = (ctx) => ({
  map: { inline: true }
})
```

Would still output an external sourcemap. I guess it's not really needed.

**Comment by michael-ciniawsky** [comment]
It would ? You mean by postcss-cli logic or bc I set the fallback `options.map` option wrong in the example ? 😛 `postcss.config.js` should affect maps e.g enable separate file ouput via config

**Comment by RyanZim** [comment]
@michael-ciniawsky I'm asking if we should support this behavior; it doesn't work that way now.

**Comment by michael-ciniawsky** [comment]
@RyanZim  It currently overrides `config.options.map`.

```bash
postcss src/index.css -o dest/index.css -w
```

**postcss.config.js**
```js
module.exports = ({ file, options, env }) => ({
  map: { inline: false },
  parser: file.extname === '.sss' ? 'sugarss' : false,
  plugins: {
    'postcss-import': { root: file.dirname },
    'postcss-nested': {},
    'cssnano': env === 'production' ? {} : false
  }
})
```

```
dest/index.css
dest/index.css.map
```

**Comment by RyanZim** [comment]
@michael-ciniawsky So in the above example, if you ran 

     postcss src/index.css -o dest/index.css -w

instead; would the output change?

**Comment by RyanZim** [comment]
Oops, typo: if you ran

    postcss src/index.css -o dest/index.css -w -m

What should the output be?

**Comment by michael-ciniawsky** [comment]
You need to set `map: ctx.options.map` in `postcss.config.js` for this to work

**Comment by RyanZim** [comment]
:+1: Makes sense.

---

Here's a rough draft of a migration guide: https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2----v3. Let me know what you think.

**Comment by michael-ciniawsky** [comment]
Yeah more or less 😛 , if someone uses `postcss.config.js`+ wants to set PostCSS Options via CLI sometimes he/she needs to reference it in `postcss.config.js` or hard code it and use CLI for file I/O only. I document this with the outstanding `ctx` docs. I also found no critical bugs in terms of usage until no so imho a `postcss-cli@3.0.0-beta` is justifiable. Only the UI is a little buggy, why is the 'global' spinner instance not an applicable way in your opinion? You said something about running `postcss-cli` in the background, but I don't fully get that before 🙃 

Migration Guide looks good 👍 , but maybe someone else of the pre v3 era should take a look aswell

**Comment by RyanZim** [comment]
> Only the UI is a little buggy, why is the 'global' spinner instance not an applicable way in your opinion? You said something about running postcss-cli in the background, but I don't fully get that before :upside_down_face:

When processing multiple files at once, it doesn't always print a full list of files processed with a global spinner.

What I was saying about background processing is that I don't want a spinner displaying the `Watching for file changes` message. I just want it `console.warn`ed.

---

> Migration Guide looks good :+1: , but maybe someone else of the pre v3 era should take a look aswell

Yeah, why not. @watilde @pirxpilot could you see if https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2----v3 makes sense to you?

**Comment by watilde** [comment]
@RyanZim Looks neat! The context parameter in the third example would be useful for fine adjustment and debug :)

**Comment by michael-ciniawsky** [comment]
> When processing multiple files at once, it doesn't always print a full list of files processed with a global spinner.

@RyanZim  kk, I need to check that, but can I propose another solution via PR ?

> What I was saying about background processing is that I don't want a spinner displaying the Watching for file changes message. I just want it console.warned.

@RyanZim  Yep agreed, there must be no running spinner while waiting for changes, I also seems like this had notable performance impacts. Ora also writes to `process.stderr` so  a [`setTimeOut`] and `spinner.stopAndPersist()` === console.warn()`. 

![bug](https://cloud.githubusercontent.com/assets/5419992/22758912/db0b89d6-ee50-11e6-9471-34968464849e.png)


For warnings `spinner.warn()` there is a PR [#36](https://github.com/sindresorhus/ora/pull/36) open @ora

**Comment by RyanZim** [comment]
> kk, I need to check that, but can I propose another solution via PR ?

I'd say let's get beta shipped at least. We can always improve later.

**Comment by michael-ciniawsky** [comment]
@RyanZim yep, yep of course :shipit: , see what critical bugs maybe occur, the above are just cosmetics we resolve before *v3@latest* 🙃

**Comment by RyanZim** [comment]
Here's a draft of the CHANGELOG: https://github.com/postcss/postcss-cli/wiki/v3-changelog-draft. Did I miss anything?

**Comment by michael-ciniawsky** [comment]
@RyanZim Nope, good to go imho, I fix the UI bug from above (just a `'\n'` 😛 ) and add it to #86, then it's :shipit: time 💪 🙃

**Comment by RyanZim** [comment]
postcss-cli v3.0.0-beta is shipped: https://github.com/postcss/postcss-cli/releases/tag/v3.0.0-beta. Please report any bugs in the docs, code, or release notes. Note that the v3 code is still in the develop branch.

---

@michael-ciniawsky Feel free to contribute UI changes before v3.0.0.
