### ISSUE TITLE
Can't pass options to local plugin

### ISSUE THREAD

**Issue by Ryuno-Ki** [postcss/postcss-cli#84]
Today I encountered a problem with the usage of both, the CLI and the config option.

Say I have a postcss plugin `foo` stored in `plugins` (so the path to file is `./plugins/foo.js`).
Assume, that my plugin expects an option called `bar`.

On CLI I would invoke the CLI this way: `node_modules/.bin/postcss --use './plugins/foo' --./plugins/foo.bar "baz"`.

After looking into why my plugin didn't received any options, I encountered [here](https://github.com/postcss/postcss-cli/blob/90ad9df2d34737d2663f9489e79d6a7f6d1be825/index.js#L114), that `name` contains the leading dot, whereas in `argv` it was stripped away. Hence the check always fails.

I couldn't reproduce the behaviour with yargs (v4.8.1 as used in my project), so I assume postcss-cli does transform it somewhere.

If I put the options into a JSON file as described [here](https://github.com/postcss/postcss-cli/blob/c60c3d0f7bcd330529cfa5f61ce8f11a42eab144/Readme.md#--config-c) it still not works for the same reason.

So either the leading dot must not be stripped away or the check should ignore it if it looks for presence in `argv`.

**Comment by RyanZim** [comment]
@Ryuno-Ki We are going to be releasing v3 soon; hopefully by Saturday. That will completely overhaul the way you pass options to plugins, so not going to fix this for the small period that remains for v2. Sorry for the inconvenience.
