### ISSUE TITLE
v3 release

### ISSUE THREAD

**Issue by RyanZim** [postcss/postcss-cli#85]
Let's face it: I don't think we're going to make our self-imposed deadline of having v3 shipped by tonight. There are still some odds and ends to clean up, and I'm too tired to trust myself releasing a major version tonight.

How about if we release `v3.0.0-beta` ~Monday and allow people to test it? Then when I get off my crazy hours in about 2 weeks, we can release v3.0.0 proper.

@michael-ciniawsky @ai

**Comment by michael-ciniawsky** [comment]
Yep, imho ship a beta and let folks test it  in && out first, I also have quite much on the plate atm and testing 'in the wild'  is always a good idea :) 👍

**Comment by RyanZim** [comment]
OK, will ship beta when I get a chance.

**Comment by RyanZim** [comment]
Sorry so long.

`develop` branch is correctly tagged, ready to publish to npm.

@ai can you add me on npm? My npm username is [`@ryanzim`](https://www.npmjs.com/~ryanzim)

**Comment by ai** [comment]
@RyanZim done

**Comment by RyanZim** [comment]
v3.0.0-beta is shipped: https://github.com/postcss/postcss-cli/releases/tag/v3.0.0-beta. Please report any bugs in the docs, code, or release notes. Note that the v3 code is still in the `develop` branch.

**Comment by RyanZim** [comment]
v3.0.0 is shipped! :tada:
