### ISSUE TITLE
postcss  --watch generating empty files

### ISSUE THREAD

**Issue by teochengyong** [postcss/postcss-cli#87]
# Bug Information
- **Post-CSS CLI version**: 2.6.0
- **Node version**: 6.9.1
- **Npm version** : 3.10.8

**Description:**
Postcss watch is run using npm run watch as follow:

  "scripts": {
    "build-css": "postcss --config postcss.json",
    "watch": "npm run build-css -- --watch",
  },

css files are generated when npm run watch runs the first time, however some times empty css files are generated randomly.
 
The issue is here related to another issue in babel https://github.com/babel/babel/issues/4332 where chokidar is used as a watcher.

**Comment by michael-ciniawsky** [comment]
@teochengyong Why are working on `v3` atm (on the finish line) and won't fix anything related to `v2`, since `v3` is a complete overhaul. You could do the following for now 

```bash
npm uninstall postcss-cli && npm -i -g|-D postcss/postcss-cli#develop
```

```
postcss -v 
```

 > ⚠️  If you see a red alchemist stone logo, you're on v3 even it displays `v2.6` atm

Then see the [Migration Guide](https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2----v3) for upgrading `postcss.config.json` to 'new' standard format (`postcss.config.js`) used in nearly all PostCSS middlewares (cli, gulp, webpack, vue) from now on.

And please feel free to report back any migration issues / bugs 🙃

**Comment by teochengyong** [comment]
@michael-ciniawsky thanks for letting me know, i will try to see if this happens in the V3 version.

**Comment by RyanZim** [comment]
v3.0.0-beta just shipped!

**Comment by RyanZim** [comment]
@teochengyong Is this still an issue for you with v3.0.0-beta?

**Comment by alexpi** [comment]
I may have a related issue. If I watch for multiple files, like:
`postcss src/css/*.css -d assets/ -w`, the files are compiled at first, but when I change something in the css, I get a "Error: ENOENT: no such file or directory" error. When I specify a certain input file to watch, it works as expected. I am on 3.0.0-beta.

**Comment by RyanZim** [comment]
@alexpi That looks like a separate issue; please open a new issue for that. Thanks!

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by mdmoreau** [comment]
@RyanZim I'm still running into this issue, but adding the chokidar options from https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel/dir.js#L146-L149 seems to have fixed it for me locally. They're the same ones from the original thread that got added to babel-cli.
