### ISSUE TITLE
config file no longer works in v3.0.0-beta

### ISSUE THREAD

**Issue by herkulano** [postcss/postcss-cli#90]
I have the following command in `package.json`: 
```
"scripts": {
    "css": "postcss -c .postcss.json"
  }
```

in `.postcss.json`:
```js
{
  "use": ["stylefmt", "postcss-sorting"],
  "input": "src/**/*.css",
  "local-plugins": true,
  "replace": true,
  "stylefmt": {...},
  "postcss-sorting": {...}
}
```

It works well in v2 but upgrading to v3-beta throws:
```
Warning: No files passed, reading from stdin
Error: Did not receive any stdin
```

**Comment by michael-ciniawsky** [comment]
[Migration Guide](https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2-to-v3)

**Comment by RyanZim** [comment]
Also, v3 docs are here: https://github.com/postcss/postcss-cli/tree/develop

**Comment by amaurycatelan** [comment]
ohh.. I found exactly what I was looking for! (migrating from v2 to v3) 
Thank you! 😃  👍
