### ISSUE TITLE
Config file doesn't seem to work as expected

### ISSUE THREAD

**Issue by dvf** [postcss/postcss-cli#92]
Not sure what I'm doing wrong, I'm following the example in the README, PostCSS doesn't seem to respect the `input` key in the config file when running `npm run postcss`. However, it works if I hard-code the actual input file in the script definition in `package.json`.

Also, when I do `npm run postcss`, the command doesn't watch the file. It just exits.

**postcss.config.json**
```
{
  "use": [
    "autoprefixer",
    "postcss-import",
    "postcss-simple-vars",
    "postcss-extend",
    "postcss-nested",
    "postcss-mixins"
  ],
  "input": "static/css/src/base.css",
  "output": "static/css/base.min.css",
  "local-plugins": true,
  "watch": true,
  "autoprefixer": {
    "browsers": "> 5%"
  }
}
```

**package.json**
```
  ...
  "scripts": {
   "postcss": "postcss --config postcss.config.json"
  }
```

**Comment by michael-ciniawsky** [comment]
[Migration Guide](https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2-to-v3)

**Comment by dvf** [comment]
Thanks @michael-ciniawsky, should update Readme.

**Comment by michael-ciniawsky** [comment]
@dvf It's on the develop branch atm, bc v3 is still in beta

**Comment by dvf** [comment]
Sorry @michael-ciniawsky but is there a clear example that shows how to set up `postcss-cli` with a config file freshly from scratch? The docs aren't clear for someone doing this for the first time.

The migration guide points you to https://github.com/michael-ciniawsky/postcss-load-config which tells you to add the same options in `package.json` and `.postcssrc` (or `postcss.config.js`).

**Comment by michael-ciniawsky** [comment]
Alright :)  what plugins do like to use ? You can either use on of those 3 options, while `postcss.config.js` is recommended one amongst them.

```bash
postcss src/index.sss -o dest/index.css --parser sugarss 
```

```js
module.exports = (ctx) => {
   parser: ctx.file.extname === '.sss' ? options.parser : false, // options.parser === 'sugarss'
   map: options.map // Always set this to inherit --map argument => 'inline' by default
   plugins: {
     'postcss-plugin': {...options},
      ...plugins
   }
}
```

**Comment by RyanZim** [comment]
@michael-ciniawsky Yeah, default branch should be changed, but I don't have permissions to do so. @ai can you change the default branch to `develop`? (We will change it back when v3.0.0 is released)

**Comment by RyanZim** [comment]
Default branch fixed.

**Comment by michael-ciniawsky** [comment]
@dvf Does it work now? What's the status?

**Comment by dvf** [comment]
@michael-ciniawsky thanks for your help! I got it working. Much appreciated.
