### ISSUE TITLE
`from` field in `postcss.config.js` does not work in v3?

### ISSUE THREAD

**Issue by leader22** [postcss/postcss-cli#93]
Define `postcss.config.js` like below

```js
module.exports = {
  from: './src/style.css',
  to: './dist/style.css',
  plugins: {
    'postcss-nested': {}
  },
};
```

and running

```sh
postcss -c ./postcss.config.js
```

ends up with error. `Error: Did not receive any stdin`

Currently, v3 not seems to treat `from` field as `input`.
Is this a bug? or my misunderstanding?

I know `postcss-cli@3` docs says `⚠️ If no input files are passed, it reads from stdin.`
But with `postcss-cli@2`, I could achieve this with `input` field in `postcssrc.json`.

What should I do?

Thanks.

**Comment by michael-ciniawsky** [comment]
Well that maybe needs (re)discussion, but we followed the path to **not** support `options.from` `options.to` via `postcss.config.js`, bc the common config (`postcss.config.js`) should work with all PostCSS Middlewares (CLI, Gulp, Grunt, webpack) seamlessly. Current fix is 

```
postcss src/style.css -o dist/style.css
```

You don't need to set the `-c|--config` when config is in root `./` or the same directory* as the file :). You could even use mutlipe configs and the nearest config found would be applied to the file

*
```
|–src
|  |–style.css
|  |–postcss.config.js
|–package.json
```

**Comment by leader22** [comment]
@michael-ciniawsky 

> but we followed the path to not support 

oh.., I see, thanks.

My current work around is just

```
postcss src/style.css
```

cause, `to` filed seems working as `output` now.
Will not it be supported in near future?

**Comment by michael-ciniawsky** [comment]
It will be difficult to implement, bc the config is loaded after the input :) I will try, but ask @RyanZim, since he's the official maintainer of postcss-cli 😛

**Comment by RyanZim** [comment]
Yep, don't see the point of allowing setting the input with `from`. I just need to add this to the release notes/migration guide.

Currently, setting `to` does set the output file. @michael-ciniawsky Do you think this is desirable, or should we disable this behavior?

**Comment by michael-ciniawsky** [comment]
@RyanZim It's bc of `Object.assign` in the `css`  function, I'm not in favour of it tbh, since we agreed upon leaving I/O to the CLI enterily. But it doesn't hurt anyone atm, also we definitely need an Error thrown for `options.from/options.to` let me think about it 😛

**Comment by RyanZim** [comment]
Sure, give it some thought. Also, would you be disallowing setting `options.to`/`.from` for all users of postcss-load-config?

**Comment by michael-ciniawsky** [comment]
@RyanZim I'm not sure about that, bc the pure Node API should have access to all PostCSS Options, but I admit that it can be confusing with common PostCSS middlwares and needs consideration.

**Comment by RyanZim** [comment]
@michael-ciniawsky Have you had time to think about this more?

Personally, I'm in favor of erroring when `options.from` is set in the config. Setting `options.to` does have a (small) use-case for when you're writing to stdout.

**Comment by michael-ciniawsky** [comment]
@RyanZim Yep, i'm also in favour to disable it (`options.to`), setup should be consistent and the most straightforward way to handle various I/O operations is via CLI arguments. I add a note to the docs in addition with a few smaller fixes but let's land #94 beforehand

**Comment by RyanZim** [comment]
#94 merged, go ahead with what you want to do.

**Comment by RyanZim** [comment]
@michael-ciniawsky How's your PR coming along?

**Comment by RyanZim** [comment]
@michael-ciniawsky ping?

**Comment by Ryuno-Ki** [comment]
Ah, hm.

An argument for allowing `options.to` would be the possibility to send the output to `/dev/null` cross-platformly:
```js
'use strict';

let path = require("path")
let isWin = /win32/.test(process.platform)
// Kudos http://stackoverflow.com/a/36746090
let dir = isWin ? "" : "dev"
let output = isWin ? "\\\\.\\NUL" : "null"

module.exports = {
  // ...
  "to": path.join(dir, output)
}
```

I can imagine that this is already solved with #98.

**Comment by RyanZim** [comment]
@Ryuno-Ki Why would you want to send the output to `/dev/null`? Why are you processing the CSS if you're throwing the result away? #98 is regarding the noisy `stderr` output; not the CSS sent to `stdout`.

**Comment by Ryuno-Ki** [comment]
See #98. Because for my use case I'm interested in STDERR, not STDOUT.

**Comment by RyanZim** [comment]
Fixed in 55466e2.

**Comment by RyanZim** [comment]
v3.0.0 is shipped! :tada:

**Comment by thomasklein** [comment]
Hi guys!

I would like you to reconsider the decision to remove the two valid postcss.config params `to` and `from`. A simple use case: Depending on an env variable (e.g. `NODE_ENV`) the input/output file changes. Since I use the CLI mostly as part of an npm script, I would have to get quite verbose now whereas before I could dynamically assign the input/output files.

**Comment by RyanZim** [comment]
@thomasklein You have a point about allowing `to`. @michael-ciniawsky How do you feel about this?

Due to the way the config file is loaded, we cannot support `from`. I don't see that changing in the future.

**Comment by thomasklein** [comment]
Please help me out to understand - from what I gathered in this thread:

> It will be difficult to implement, bc the config is loaded after the input :)
> bc the common config (postcss.config.js) should work with all PostCSS Middlewares (CLI, Gulp, Grunt, webpack) seamlessly
> Due to the way the config file is loaded, we cannot support from

From looking at the source https://github.com/postcss/postcss-cli/blob/master/index.js#L44 I understand you are parsing all arguments. So I think implementing a conditional based on the position and content of the params should make it possible to treat this 

```
postcss input.css -c config.js
// `to` is in config.js
```
or this
```
postcss -c config.js
// `from` is in config.js
```

Happy to hear about your feedback - and thanks for this project!

**Comment by michael-ciniawsky** [comment]
@RyanZim I'm not particular against it, but when `options.to` works based on the config + `ENV` the source still needs to be set via CLI and that's not really clean separation. But I see the usecase @thomasklein is referring to, still the same can be basically achieved via npm scripts (which is likely to be needed anyways to set the `ctx.env`)

**package.json**
```json
{
   "scripts": {
      "css:development": "NODE_ENV="development" postcss src/*.css -d temp/ -w"
      "css:production": "NODE_ENV="production" postcss src/*.css -d public/"
    }
}
```

**Comment by RyanZim** [comment]
@thomasklein The problem with `from` is, we don't know where to look for the config file. (Note that the new `-c` option is different from the v2 option.) We look up `postcss.config.js` starting at the input css file. If the input css file location is in the config, we don't know where to look for the config.

**Comment by thomasklein** [comment]
Thanks for you feedback.
> The problem with from is, we don't know where to look for the config file.

Yes, with your current code structure that is the case. https://github.com/postcss/postcss-cli/blob/master/index.js#L183

However, let me propose the following flow in which you would first check if the `--config/-c` param is present and in this case load the contents into, e.g., a var `configFile`. Then

```
var input = argv._ || configFile.from
var output = argv.output || configFile.to
```

**Comment by RyanZim** [comment]
@thomasklein We have an X/Y problem. The config gets the input file in the context: https://github.com/postcss/postcss-cli#context. So we need to have the CSS file before we can get the config.

**Comment by thomasklein** [comment]
Ah ok, slowly diving into it :). So it's basically because https://github.com/michael-ciniawsky/postcss-load-config is used to load the config and it allows to export the config also as a function with a context argument. My last question would be: is such a configuration than still compatible with postcss itself or would I then be bound to postcss-cli?

**Comment by RyanZim** [comment]
> My last question would be: is such a configuration than still compatible with postcss itself or would I then be bound to postcss-cli?

Not sure what you're asking; postcss-load-config is a userland module that the postcss core devs really like, so core is pushing for runners to use it.

**Comment by michael-ciniawsky** [comment]
`postcss-loader` (webpack), `gulp-postcss` (Gulp), `postcss-cli` (CLI), `vue-loader` (Vue), 'styled-jsx` (Zeit/Next.js), `Laravel Mix` (Laravel [PHP]) all support this common config format, that's the point about it :stuck_out_tongue:

**Comment by thomasklein** [comment]
Thanks for the clarification and insights!

**Comment by jonathantneal** [comment]
If no input is specified from the CLI, I see no reason not to allow the config to determine the `to` and `from`.
