### ISSUE TITLE
error when i set Context

### ISSUE THREAD

**Issue by shirleyMHao** [postcss/postcss-cli#96]
my postcss.config.js is:
```
module.exports=(ctx) =>({
    dir: 'dist' + ctx.file.dirname,
    use:[
      'postcss-will-change',
      'autoprefixer'
        ]
})
```
when I run `postcss src/*.css src/**/*.css -c postcss.config.js`
I got an error `Must use --dir or --replace with multiple input files`

**Comment by michael-ciniawsky** [comment]
@shirleyMHao Your config is not compatible with postcss-cli >= `v3.0.0`, the config format changed in favour of `postcss.config.js` common format, useable across all PostCSS Build Tools (CLI, Gulp, webpack), see the [Migartion Guide](https://github.com/postcss/postcss-cli/wiki/Migrating-from-v2-to-v3) for more Information.

**CLI/npm**
```sh
postcss src/*.css src/**/*.css -d dist/ 
```

**postcss.config.js**
````js
module.exports = (ctx) => ({
  plugins: {
    'postcss-will-change': {...options} // options = Plugin Options 
    'autoprefixer': {} // {} = Plugin Default Options
  }
})
```

**Comment by shirleyMHao** [comment]
can i use the ctx to mapping outfolder to inputfolder?

**Comment by michael-ciniawsky** [comment]
@shirleyMHao Nope sry, File I/O must be specified via CLI arguments, because there is no convenient way to support the different I/O options in the config and across build tools.

**Comment by RyanZim** [comment]
Closing as per @michael-ciniawsky
