### ISSUE TITLE
Allow to disable printing logo

### ISSUE THREAD

**Issue by bkolodziej** [postcss/postcss-cli#99]
There should be an option to disable printing of logo... or simpler: just get rid of this ASCII-art. It clutters the output of build script too much. Especially if you (like me) have more than one CSS file to output.

Adding `2> /dev/null` does not help as it hides useful communicates as well.

**Comment by RyanZim** [comment]
Possible duplicate of https://github.com/postcss/postcss-cli/issues/98.

**Comment by RyanZim** [comment]
v3.0.0 is shipped! :tada: Logo is not printed during normal use in v3.0.0
